### ISSUE TITLE
Not really an issue :-)

### ISSUE THREAD

**Issue by hrbrmstr** [thomasp85/ggforce#1]
ggalt has `geom_xspline()` which might fulfill the needs of your pending `geom_spline()`

Great package!

**Comment by thomasp85** [comment]
It does sound quite like what I had in mind. I'll move it to ultra low priority and put a link to ggalt next to it. 

Hadn't seen your package before - what is the plan with it? Like ggforce or more feature frozen?

**Comment by hrbrmstr** [comment]
I was going to see what other `stats_` might be good to add once ppl
realized ggplot2 2.0 was extensible (I figured Twitter et al wld have many
"boy it'd nice if ggplot2 had…" tweets in the coming months/years).

There's also ggfortify (it sounds like a directory of ggplot2 add-ons is
almost necessary at this point).

**Comment by thomasp85** [comment]
I'm going to add a related work to the bottom of the readme to point to similar project. I'm not really a twitter user so you have a source of inspiration I won't have - but just getting to the bottom of my pending list will take some time. Having done a lot of work in D3.js I'll probably draw a lot of inspiration from there as well in terms of visual encodings that could be nice to have in ggplot2 (some only makes sense in interactive plots but most makes sense in a static ggplot2 world)...
