### ISSUE TITLE
Examples please

### ISSUE THREAD

**Issue by pavopax** [thomasp85/ggforce#10]
Example plots and code in README will do wonders to motivate me to install and use this. Thanks!

**Comment by thomasp85** [comment]
While I generally agree I find it odd that you are motivated enough to create an issue but not enough to install it and read the extensive vignette...

Examples will come to the readme in due time

**Comment by pavopax** [comment]
I see your point! Let me clarify the situation which perhaps is not uncommon: I was reading this on mobile on a Friday night, while also looking at a few of the other latest gg-like packages , and this README was the only thing I saw. If I saw compelling use cases (pictures) right away in the README, I'd email the page to myself with "check this out tomorrow". 

Definitely a case of laziness on my part! but it seems to me that a graphics package could use a quick header graphic or something to compel other people just stumbling about to take the plunge and install this when they get a chance!

**Comment by Deleetdk** [comment]
I agree with @pavopax. It would be nice with a knitr of examples. The vignette also does not have visual examples, just code to make them.

I often wonder which geom to use for a particular dataset and then I skim the gg extension packages' githubs for inspiration.
