### ISSUE TITLE
facet_wrap_paginate sometimes loses it's layout on the last page

### ISSUE THREAD

**Issue by ashimkapoor** [thomasp85/ggforce#100]
Here is a reprex:

library(ggplot2)
library(ggforce)

# Compare this :
ggplot(diamonds) +
  geom_point(aes(carat, price), alpha = 0.1) +
  facet_wrap_paginate(~cut:clarity, ncol = 3, nrow = 3, page = 1)

# With this
ggplot(diamonds) +
  geom_point(aes(carat, price), alpha = 0.1) +
  facet_wrap_paginate(~cut:clarity, ncol = 3, nrow = 3, page = 5)

Best Regards

**Comment by thomasp85** [comment]
Can I get you to install the development version from GitHub - I believe it should be fixed

**Comment by ashimkapoor** [comment]
Dear Thomas,

Yes I can confirm it seems to be working.
