### ISSUE TITLE
Consider splitting up into multiple packages

### ISSUE THREAD

**Issue by flying-sheep** [thomasp85/ggforce#102]
Some dependencies have a rat tail of further dependencies. E.g. `concaveman` uses the `V8`, which depends on the native `libv8`, which isn’t on every linux system.

And building a behemoth like libv8 just to get some unrelated geom in this package is much to ask.

So it would be cool if I could e.g. `install.packages('ggforce.voronoi')` which just depends on `ggplot`, `scales` and `deldir`. `ggproto` would just be a wrapper reexporting all `ggforce.*` packages.

**Comment by thomasp85** [comment]
I’m unlikely to split it up, but I’ll be interested in looking into slimming down dependencies (have already done this for the units package and concaveman is a good possibility as well)

**Comment by thomasp85** [comment]
The dependencies for ggforce has now been slimmed down

**Comment by flying-sheep** [comment]
nice! thank you!
