### ISSUE TITLE
Installation problem from github

### ISSUE THREAD

**Issue by crotoc** [thomasp85/ggforce#112]
Hi, thanks for your great pakage first! It helps me generate a lot of figures! 
I met a problem that the function can't insert rows to the last page and found that you have addressed it in this dev version. I tried to install using github_install  but it seems like that it requires V8 lib. I am on a server having no root privilege. I try to install libv8 from source and it's nearly impossible. Do you have  other way to work around. Thanks very much!

**Comment by thomasp85** [comment]
V8 is no longer a required dependency
