### ISSUE TITLE
Add facet_col/facet_row

### ISSUE THREAD

**Issue by mkoohafkan** [thomasp85/ggforce#114]
*This issue was originally posted at https://github.com/tidyverse/ggplot2/issues/2933*

It would be great to see new faceting options `facet_row` and `facet_col` which would behave like `facet_grid` but allow the user to specify whether facet labels are placed on the side or on top of each facet. The key feature I am missing right now is the ability to use the `space` argument from `facet_grid` with a one-column layout where facet labels are *above* of each facet.

reproducible example:

```
library(tidyverse)

p <- mtcars %>%
  rownames_to_column() %>%
  ggplot(aes(x = disp, y = rowname)) + geom_point()

# Issue: labels not on top, but on the side:
p + facet_grid(carb ~ ., scales = "free_y", space = "free_y")

# Issue: panel size not proportional (no parameter: space = "free_y"):
p + facet_wrap(~ carb, ncol = 1, scales = "free_y")

# potential solution:
##p + facet_col(~ carb, scales = "free_y", space = "free_y")
```

**Comment by MattCowgill** [comment]
this would be really useful

**Comment by soroosj** [comment]
Agreed

**Comment by ggabernet** [comment]
I ran into the exact same issue!

**Comment by camiloramirezgo** [comment]
This would be really useful!
