### ISSUE TITLE
stat_sina() doesn't match geom_violin()

### ISSUE THREAD

**Issue by clauswilke** [thomasp85/ggforce#117]
When using `stat_sina()` together with `geom_violin()`, it routinely happens that points fall outside the violins. This is the case because `stat_sina()` uses a different algorithm to calculate densities than does `geom_violin()`. I'm not quite sure why it does that; to me the `stat_sina()` code looks overly complex. We just need to calculate the density outline exactly like ggplot2 does, turn it into an interpolating function, and then use that function to jitter individual points. The result is a perfect match.

``` r
library(ggplot2)
set.seed(1234)

# ggforce implementation
ggplot(iris, aes(x = Species, y = Sepal.Length)) +
  geom_violin() +
  ggforce::stat_sina()
```

![](https://i.imgur.com/h0gt4bb.png)

``` r

# alternative implementation that matches
ggplot(iris, aes(x = Species, y = Sepal.Length)) +
  geom_violin() +
  dviz.supp::stat_sina()
```

![](https://i.imgur.com/lJNKY4j.png)

<sup>Created on 2019-02-21 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

The code for my alternative implementation can be seen here:
https://github.com/clauswilke/dviz.supp/blob/master/R/stat_sina.R

It is virtually identical to `stat_ydensity()` from ggplot2. It also uses one unexported function from ggplot2, but that could be copied and pasted into the ggforce code.

**Comment by thomasp85** [comment]
I’m generally in favour of this change, but I’ll let it be up to @sidiropoulos et al, as it is their algorithm/approach

**Comment by sidiropoulos** [comment]
I'm also very much for it. I wrote `geom_sina()` while knowing very little about ggplot2. 
@clauswilke do you want to create a pull request?

**Comment by clauswilke** [comment]
I'd prefer if somebody else could take this on. I've got a ton of stuff on my plate right now. My implementation works but it requires some thought to make sure it doesn't break existing code using `geom_sina()` and/or warns users that certain parameters have been deprecated.

I'm happy to explain how I implemented it, though. The key idea is to turn the kernel density estimate into an approximating function:
https://github.com/clauswilke/dviz.supp/blob/d5fa1e7495f3e871bcd6c6069204da565607278d/R/stat_sina.R#L69
and then to use that to calculate the appropriate density for each data point in the original data set:
https://github.com/clauswilke/dviz.supp/blob/d5fa1e7495f3e871bcd6c6069204da565607278d/R/stat_sina.R#L77

This can then be used to calculate the violin width at each point and to jitter:
https://github.com/clauswilke/dviz.supp/blob/d5fa1e7495f3e871bcd6c6069204da565607278d/R/stat_sina.R#L92-L104

**Comment by thomasp85** [comment]
I’ll take this. I’m beginning to prep for a new release soonish anyway

**Comment by thomasp85** [comment]
@clauswilke are you ok if I more or less lift your implementation and adapt it?

**Comment by clauswilke** [comment]
Yes, of course. In any case, it’s all copied from ggplot2.
