### ISSUE TITLE
Move to MIT license

### ISSUE THREAD

**Issue by thomasp85** [thomasp85/ggforce#125]
I've been gradually moving my repos to the more permissive MIT license and wish to do that for ggforce as well. @sidiropoulos, @lepennec, @andrewheiss, and @daniel-wells you have all made significant contributions through new features or bug fixes and thus have a say in license changes (as it concerns code you've written).

If you have any objections to moving to MIT licensing please respond to this issue, otherwise the change will go in effect in one week.

If you have any questions concerning this, please let me know as well. Thanks for your contributions.

**Comment by andrewheiss** [comment]
I'm fine with MIT. All my personal stuff is MIT already and I'm a big fan.

**Comment by lepennec** [comment]
Obviously, no issue for me!

**Comment by sidiropoulos** [comment]
Same here
