### ISSUE TITLE
Combining facet_zoom with geom_histogram

### ISSUE THREAD

**Issue by geotheory** [thomasp85/ggforce#126]
I wonder about feasibility of enhanced support for geom_histogram in future? Specifically the question of applying either a specific different `binwidth` to the zoomed facet, or by applying the same `bin` argument.  The current implementation seems to zoom the post-binned summary:

```
set.seed(0)
x = tibble(date = as.Date('2018-01-01') + rnorm(500, sd=3)^3)
p = x %>% ggplot(aes(date)) + geom_histogram(bins = 50, col = 'white', size=.1) + theme_light()
p + facet_zoom(x = date >= "2017-12-01" & date <= "2018-02-01", zoom.size = 1)
```

<img width="710" alt="image" src="https://user-images.githubusercontent.com/1282581/53738368-ec268d00-3e86-11e9-8351-fb973936e148.png">

It would be really useful to be able to drill into histograms to explore spikes and strange distributions.

**Comment by liuyanguu** [comment]
This can be done as explained at the end of this webpage: https://www.data-imaginist.com/2019/the-ggforce-awakens-again/
