### ISSUE TITLE
Feature Request: Add highlights spanning facets

### ISSUE THREAD

**Issue by snystrom** [thomasp85/ggforce#128]
The goal of this visualization is to draw a rectangular box spanning facet boundaries for the purpose of highlighting a range of data along a continuous scale.

I think this would be a relatively straightforward addition (perhaps even from extending `facet_zoom` code) which would have many practical applications. 

Examples of this can be found here:
[Here](https://stackoverflow.com/questions/51088379/ggplot2-add-annotation-spanning-facet-edges)

You could also imagine this being a useful geom for allowing `facet_zoom()` on a faceted plot where the highlight rectangle is drawn by the highlight geom and the zoom-expansion highlight is drawn by `facet_zoom`.

**Comment by thomasp85** [comment]
As this doesn't fall under the standard things you can do with the ggplot2 API (graphics spanning panels) it is unlikely to get into ggforce so I'm closing it
