### ISSUE TITLE
Strenuously suggesting deldir

### ISSUE THREAD

**Issue by jmw86069** [thomasp85/ggforce#129]
First, I love this update! Really looking forward to using the new geoms!

I noticed 10 days ago you moved "deldir" to Suggests. For me, not having "deldir" caused the Voronoi/Delauney plots to display nothing. I appreciate trimming dependencies, makes sense.

I was going to suggest throwing a warning message, then I realized (haha omg) that I have warnings turned off, and that you *actually do* throw a warning message. (Because of course you would do that obvious thing.) So... kudos for that, and sorry for even considering otherwise.

And since it took me too long (15 minutes) to track down that I needed to install "deldir", yes I'm going to reluctantly turn on warnings. Apparently I need to see them.

I also suggest you might mention something like "If you have any issues with the new geoms not displaying, try installing the packages in 'Suggests'. Some packages were moved there by request to reduce dependencies." It might also warrant a snarky comment about how this issue would only affect someone still using R with warnings turned off. Maybe it's only me, then I'll really feel bad.

But mostly I wanted to say great work, I'm really excited to try out the new stuff!

**Comment by thomasp85** [comment]
It should error, not warn, if deldir is not available... Are you sure it was a warning? If so, can you share your code?

**Comment by jmw86069** [comment]
Okay, here are minimal steps I can use to produce the warning message. (It looks like a warning anyway.)

```
## Remove deldir for testing
remove.packages("deldir");
unloadNamespace("deldir");
options("warn"=TRUE);
library(ggforce);
ggplot(iris, aes(Sepal.Length, Sepal.Width)) +
   geom_voronoi_tile(aes(fill=Species, group=-1L)) +
   geom_point()
```

The message is:

> Warning: Computation failed in `stat_voronoi_tile()`:
> The delauney-based geoms and stats require the deldir package

**Comment by thomasp85** [comment]
oh, yeah... ggplot2 catches errors in the stats and gloms and displays them as warnings... nothing to do about that...

I must admit that I've never met anyone who have turned off warnings, so I'll treat this as a singular case and close
