### ISSUE TITLE
Cannot install ggforce (R version 3.3.2 (2016-10-31))

### ISSUE THREAD

**Issue by mruessler** [thomasp85/ggforce#13]
Using `devtools::install_github("thomasp85/ggforce")` does not work for me. The process hangs and cannot be interrupted.
I am using R version 3.3.2 on a linux machine.

**Comment by thomasp85** [comment]
Where in the process does it hang? Can you provide the installation log?

**Comment by mruessler** [comment]
A `sink("install.log", split = TRUE)` gives no output. The file size is 0 byte and nothing is printed in the R terminal.
Do you have other recommendations for receiving debugging information?

**Comment by thomasp85** [comment]
Does it not say anything in the console when run? If not have you tried to see if it works on another package. I think this might be a devtools issue then...

**Comment by mruessler** [comment]
Indeed, this is an issue with `devtools` (I am using version 1.12.0).

**Comment by solbaviangel** [comment]
In Ubuntu (Linux) you have to install -dev version of udunits. Open Terminal and install below :
sudo apt-get install libudunits2-dev

Then the installation of udunits2, ggforce and ggraph goes without any error.
You can also prefer install.packages('ggraph', dependencies = TRUE).
