### ISSUE TITLE
warning message when trying to create sanky diagram

### ISSUE THREAD

**Issue by DS-Rodrigues** [thomasp85/ggforce#131]
Hi Thomas

I am following the steps you posted in your article "The ggforce Awakens (again)" to generate a sanky diagram in R but I am getting the following warning message when trying to generate the plot:
Warning message:
Computation failed in `stat_parallel_sets()`:
non-numeric argument to binary operator 

The output I am getting is only a bar for Hospital_ID and nothing else. 'Hospital_ID', 'Patient_ID' and 'Therapy' are factor variables and 'value' is numerical. I have 750 different patients from 24 different centres who can undertake up to 10 different therapies.

My final dataset is like this:
> head(dataset)
    Hospital_ID   Patient_ID        Therapy      variable       value      id              x                 y
1         40            44455                  Infli           value            1           1       Hospital_ID       1
2         40            44455                 Infli           value             1          2       Hospital_ID       1
3         40            44455                 Infli           value             1          3       Hospital_ID       1
4         40            33376                 Etan          value             1          4       Hospital_ID       1
5         40            33376                 Etan          value             1          5       Hospital_ID       1
6         40           3655351               Infli          value             1          6       Hospital_ID       1

Would you be able to help?

Thanks so much in advance for your help!
Daniela

**Comment by DS-Rodrigues** [comment]
Just another thing, I have tried again and now it says:
> df_new <- gather_set_data(df,1:3)
Error: lazy-load database '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/ggforce/R/ggforce.rdb' is corrupt
In addition: Warning message:
internal error -3 in R_decompress1 

Thanks
Daniela

**Comment by nelsonruth11** [comment]
Was this ever resolved?

**Comment by thomasp85** [comment]
A lot has changed since the issue was filed - if I can get a reprex (see https://www.tidyverse.org/help/) I'll be happy to take a look
