### ISSUE TITLE
Shrink has no effect when combining facet_zoom and geom_ribbon?

### ISSUE THREAD

**Issue by hhau** [thomasp85/ggforce#133]
Strong possibility I am misunderstanding what the `shrink = TRUE` option is meant to do, but I would expect the y-axis on the zoomed plot to be rescaled in the following reprex?

``` r
library(ggplot2)
library(ggforce)
library(matrixStats)

x_vals <- seq(from = 0, to = 1, length.out = 100)
y_vals <- 2 + 1.2 * x_vals
y_data <- matrix(NA, ncol = 100, nrow = 500)
y_data[] <- y_vals
y_data <- y_data + rnorm(n = prod(dim(y_data)), sd = 0.1) 

plot_df <- data.frame(
  x = x_vals,
  y = rowMeans(y_data),
  y_true = y_vals,
  lowers = rowQuantiles(y_data, probs = 0.25),
  uppers = rowQuantiles(y_data, probs = 0.75)
)

ggplot(plot_df, aes(x = x)) +
  geom_line(aes(y = y_true)) +
  geom_ribbon(aes(ymin = lowers, ymax = uppers), alpha = 0.2) +
  facet_zoom(xlim = c(0.45, 0.55), shrink = TRUE)
```

![](https://i.imgur.com/hRposez.png)

<sup>Created on 2019-03-11 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

Testing suggests that `shrink` has no effect here, so I'm slightly confused about its intended effect.

**Comment by thomasp85** [comment]
`shrink` is an argument inherited from the classic facets and really only looks at whether data has changed during the statistics transformation, not with anything happening by the facet itself... It's pretty obscure so I can understand why you got confused
