### ISSUE TITLE
facet_zoom won't zoom in xlim/ylim if axis limit set before (like in y_scale_continuous)

### ISSUE THREAD

**Issue by liuyanguu** [thomasp85/ggforce#137]
facet_zoom is a great feature but surely challenging to implement... 
If ylim or xlim is set in the parent plot, it won't work to further set ylim or xlim in the zoom-in plot. The zoom in range will just follow the setting before. This is not a big issue though, just a notice. 
It might relate to issue #133 for the same reason.
I searched if there is a way to cross it in ggplot but haven't found a solution. I appreciate any advice.
```
library(ggplot2)
library(ggforce)
ggplot(iris, aes(Petal.Length, Petal.Width, colour = Species)) +
  geom_point() +
  scale_y_continuous(limits = c(0,2)) +
  facet_zoom(ylim = c(0,1), horizontal = F)
```
same for:
```
ggplot(iris, aes(Petal.Length, Petal.Width, colour = Species)) +
  geom_point() +
  coord_cartesian(ylim = c(0,2)) +
  facet_zoom(ylim = c(0,1), horizontal = F)
```

```
packageVersion("ggforce")
```
‘0.2.1.9000’

**Comment by LuZhangH** [comment]
@liuyanguu Hi, Did you manage to figure out the solution?

**Comment by Izymil** [comment]
I join the subject - It would be extremely useful to find permanent solution or at least some ad-hoc fix. I struggle with some ggplot, that by default is zoomed. What I would like to achieve is to force ggplot to draw it in full scale and than use facet_zoom to show the zoomed panel. But when I force ggplot to show the full y scale (by using 'limits' inside 'scale_y_continous" or 'coord_carthesian'), then facet_zoom does not zoom - it reproduce the same limits I set for the main plot.

**Comment by liuyanguu** [comment]
> @liuyanguu Hi, Did you manage to figure out the solution?

I think it is what it is. I guess `ggforce::facet_zoom` on purpose inherits the limits set in `scale_x_continuous` and `scale_x_continuous`. I guess to avoid conflicts.

**Comment by thomasp85** [comment]
This should now work when setting limits on the scales. There is unfortunately no way for a facet to intervene with the limits imposed by the coordinate system so that is the best I can do

**Comment by LuZhangH** [comment]
Thanks a lot!
