### ISSUE TITLE
Two-sided geom_diagonal_wide()?

### ISSUE THREAD

**Issue by jmw86069** [thomasp85/ggforce#139]
This is a new feature request, for a two-sided version of geom_diagonal_wide(). Due respect to your time, I can prototype it, but I thought you may have considered something similar for your parallel sets plots.

In the special case of an `NA` for one factor, some Sankey plots render an arc that skips that factor (except no arc in this example):
![R graph gallery Sankey plot](https://www.r-graph-gallery.com/wp-content/uploads/2017/12/322_Sankey_Change_color_node-300x300.png)

Related question: how do you see others extending ggforce? Through external packages, or contributing PR, or combination?

I really love `geom_diagonal_wide()`, especially the way it renders consistently when resizing a plot window or transforming the x-axis. I started using it for a plot type I'm developing, and I think it's fantastic.
![Two adjacent geoms, no outline](https://jmw86069.github.io/splicejam/articles/create-a-sashimi-plot_files/figure-html/plot_test_junc-1.png)

Another example with slight outline and label:
![Two adjacent geoms, slight outline](https://jmw86069.github.io/splicejam/articles/create-a-sashimi-plot_files/figure-html/plot_sashimi_gr-1.png)
The outline really helps except for the middle line.

### The main goals:

1. remove the outline in the middle of the arc, while still being able to outline the arc overall
2. position the middle of the arc at the midpoint between left and right edges (secondary goal)
3. define how high to draw the arc in the middle (differs from standard Sankey plots)

### Bonus points:

4. optionally label the arc, otherwise determining where to add a label is tricky

Aside: I got the `geom_diagonal_wide()` to render using `ggplotly()`, and it looks great!

**Comment by jmw86069** [comment]
Update: Okay, I'll admit it was presumptuous to request a new geom. I'm learning. :-)

Meanwhile, I successfully prototyped a new geom `geom_diagonal_wide_arc()` which fit the "do the simplest thing that works" paradigm. It takes two polygons, makes two diagonal_wide, then combines them into one polygon. It does not yet calculate the middle x-position after adjusting for x-axis scales, it uses what is supplied; but I should be able to figure that out. It does not have the option of labeling, and I'm not sure I'll figure that out. For now, I'll calculate label coordinates separately, then use geom_text() or geom_text_repel().

**Comment by thomasp85** [comment]
Nothing presumptuous about that. I just don’t have time to answer all issues in all my repositories right away🙂

**Comment by jmw86069** [comment]
Wow is this issue still open? (oops)
The geom is implemented in another package jmw86069/splicejam and in use for a while now.
Ah well, my mistake!
