### ISSUE TITLE
waterfall chart support (geom_waterfall or position_waterfall)

### ISSUE THREAD

**Issue by mkoohafkan** [thomasp85/ggforce#142]
I'd like to see a geom or position aesthetic for plotting waterfall charts. My primary interest is in generating cumulative histogram plots (sort of like binned empirical cumulative distribution plots) which are a special case of a waterfall plot. It is fairly straightforward to achieve waterfall plots using `geom_rect`, but the axis labeling is clunky and I don't see a good way to fake dodging for e.g. `fill` aesthetics. 

```r
df = data.frame(
  year = factor(2010:2017),
  amount = c(2000, 3400, -1100, -100, -6600, 3800, 1400, 2800)
)

df2 = df %>% 
  mutate(
    xmin = as.integer(year) - 0.5,
    xmax = as.integer(year) + 0.5,
	ymin = lag(cumsum(amount), default = 0),
	ymax = cumsum(amount)
  )

ggplot(df2) + 
  aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax) +
  geom_rect(color = "black", fill = "white") +
  scale_x_continuous(breaks = seq_along(levels(df2$year)),
    labels = levels(df2$year))
```

It looks like this functionality has been implemented as [`position_waterfall`](https://github.com/brodieG/ggbg/blob/master/R/position-waterfall.R) in [brodieG](https://github.com/brodieG)'s unpublished [ggbg](https://github.com/brodieG/ggbg) package, so it may be easy to port this functionality.

**Comment by thomasp85** [comment]
If it is already implemented I think the best course of action would be to wait for Brodie’s answer

**Comment by brodieG** [comment]
I do intend on publishing that package someday, but my horizon there is probably somewhere between six months and never, with about a 25-50% chance of never.  In terms of contributing to ggforce, I would be open to that except for the license.  I happen to be one of those GPL zealots (albeit a usually friendly and non judgmental one), but it does unfortunately mean I would not re license my code to be MIT.

**Comment by thomasp85** [comment]
We’ll cross fingers that your package make it to CRAN then🙂
