### ISSUE TITLE
facet_zoom() throws error with geom_col() and coord_flip()

### ISSUE THREAD

**Issue by UweBlock** [thomasp85/ggforce#143]
While preparing [an answer](https://stackoverflow.com/a/56000944/3817004) to [Using ggplot2, can I insert a break in the axis?](https://stackoverflow.com/q/7194688/3817004) on SO, I noticed that `facet_zoom()` does not work for horizontal bar charts, i.e., it throws an error when used together with `geom_col()` and `coord_flip()`:

```
df <- data.frame(a = c(1,2,3,500), b = c('a1', 'a2','a3', 'a4'))
library(ggforce)
ggplot(df) + 
  aes(x = b, y = a) +
  geom_col() + 
  coord_flip() +
  facet_zoom(ylim = c(0, 10))
```

> Error in scale_index[[i]] : subscript out of bounds

When `coord_flip()` is removed the code works without any error but creates only vertical bar charts.

Extract from `devtools::session_info()`:

>  version  R version 3.5.3 (2019-03-11)
>  os       Windows 10 x64              
> ...
>  ggforce     * 0.2.2    2019-04-23 [1] CRAN (R 3.5.3)
>  ggplot2     * 3.1.1    2019-04-07 [1] CRAN (R 3.5.3)

**Comment by pgcudahy** [comment]
I get the same error when trying to use geom_pointrange and coord_flip using 
```
 version  R version 3.4.4 (2018-03-15)
 os       Ubuntu 18.04.2 LTS
...
 ggforce     * 0.2.2.9000 2019-07-02 [1] Github (thomasp85/ggforce@b771cec)
 ggplot2     * 3.2.0      2019-06-16 [1] CRAN (R 3.4.4)
```

**Comment by thomasp85** [comment]
facet_zoom was never able to work with `coord_flip()` but other errors prevented the evaluation to reach the point where the facet could inspect the coord and throw an appropriate error. This is now fixed so a better error is thrown
