### ISSUE TITLE
geom_circle flip when setting axis

### ISSUE THREAD

**Issue by wzinke** [thomasp85/ggforce#144]
When using geom-circle to draw circles, and then setting the limits of the axis could lead to  artefacts of the circle instead of just cutting it at the plot edge.

```
library("ggplot2")
library("ggforce")

ROI=data.frame(X=c(274, 425, 925, 770, 310, 895, 10),
               Y=c(524, 680, 255,  75, 630, 120, 250),
               R=c(100, 100, 100, 100, 200, 200, 150))

ggplot(ROI) + 
       geom_circle(aes(x0=X, y0=Y, r=R, color='red', fill='red', alpha=.5),
                           n=720, lwd=2, show.legend=F) +
       scale_x_continuous(expand=c(0,0), limits=c(0,w)) +
       scale_y_continuous(expand=c(0,0), limits=c(0,720)) + 
       coord_equal()
```

![Circleflip](https://user-images.githubusercontent.com/1611619/57903357-4c489080-7833-11e9-9d71-98f9be2ce1f9.png)

Everything is fine when the axes are not set;

```
ggplot(ROI) + 
       geom_circle(aes(x0=X, y0=Y, r=R, color='red', fill='red', alpha=.5),
                           n=720, lwd=2, show.legend=F) + coord_equal()
```

![goodcircles](https://user-images.githubusercontent.com/1611619/57903551-1eb01700-7834-11e9-90d8-bd1eacb5c9ae.png)

**Comment by thomasp85** [comment]
This is expected behaviour. Setting limits in the scale will per definition remove out of bound values and lead to artefacts in clipped polygons... Use the coord to set limits instead (e.g. `coord_cartesian(ylim = c(0, 720))`)
