### ISSUE TITLE
Predictions from geom_bspline

### ISSUE THREAD

**Issue by fmmattioni** [thomasp85/ggforce#145]
If I have the following data:

``` r
library(tibble)
library(ggforce)

df <- structure(list(x = c(0, 2.5, 5, 7.5, 10, 12.5, 15, 17.5, 20), 
                     y = c(0.51, 0.71, 0.8, 1.12, 2.05, 3.23, 4.45, 6.83, 11.12
                     )), class = c("tbl_df", "tbl", "data.frame"), row.names = c(NA, 
                                                                                 -9L))

ggplot(df, aes(x, y)) +
  geom_point() +
  geom_bspline()
```

![](https://i.imgur.com/r059J6O.png)

<sup>Created on 2019-05-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

How can I predict `y` given an `x` value along the `bspline`? Let's say, for example, I want to predict `y` given `x = 11.3`. Looking at the source code, I believe the model is fitted through `C++`, so I couldn't retrieve it.

Thanks!

**Comment by thomasp85** [comment]
It is not really a model, so predictions are not really meaningful. Geom_bspline draws a bspline as defined by the given control points

**Comment by fmmattioni** [comment]
Ooh.. now I get it.. in your opinion, what would be the best way to fit a model like this? 

Maybe `glm(y ~ bs(x))`?

**Comment by thomasp85** [comment]
That really depends on what you want to do with the model 🤷‍♂️ `stats::smooth.spline()` is probably most akin to it
