### ISSUE TITLE
Feature Request: Allow geom_text to Follow a Line Segment

### ISSUE THREAD

**Issue by billdenney** [thomasp85/ggforce#146]
As discussed in tidyverse/ggplot2#2852, would it be reasonable to extract the geom_text along a line segment feature from ggraph to a generalized solution in ggforce?

I *think* that the process would be porting https://github.com/thomasp85/ggraph/blob/master/R/textAlong.R along with some bits from https://github.com/thomasp85/ggraph/blob/master/R/geom_edge.R to ggforce.  But, maybe I'm missing something (likely as I've not written a Geom before).

**Comment by thomasp85** [comment]
Something like that may make sense, though I think I would not port it as is... once I've build better font handling into R we should be able to draw text along any path

**Comment by billdenney** [comment]
If a rebuild of font handling is the starting point, I doubt that I'll be the right person to make a PR.  :)

One thought for the future implementation:
When generating text along a path, there is (at least) one more aesthetic that I'd want to control: justification along the path.  For example, I may want the text to start before the beginning of the path, at the beginning of the path, somewhere along the middle of the path, at the end of the path, or after the end of the path.  The way that I'd think of this feature is that there would be one additional parameter (something like `along_just` assuming that the geom is called something like `geom_text_along()`).  With that, `along_just=0` would put the reference point for the text at the beginning of the path; `along_just=1` would put the reference point for the text at the end of the path, and values for `along_just` must be within the range of `[0, 1]`.  (Where the text relative to the reference point is controlled by `hjust` and `vjust`, as with other text functions.)

A complexity that I see with this and following a path is:  How do you extrapolate the text positioning beyond the end of the path for paths that are not lines (polynomials, beziers, etc.)?  The simplest is probably to take the tangent at the end of the path and have all extrapolation as linear.  But, if `hjust=0.5` and the path is curved, the result would look odd because the text was curved and then abruptly linear.  (The same problem would also occur with text that is longer than the path.)

That said, for my use cases, I doubt that I would use anything other than `hjust` as 0 or 1 near a path end where the text is intended to be anything other than fully on or fully off the path.

One other feature to consider would be expanding or compressing the text so that it was spread along the full length of the path.  (That one seems simple when text along a path with the above justification is covered as it would just split into each individual character which is placed with `along_just` of the fraction of the way through the string.)

**Comment by thomasp85** [comment]
As there is now a fantastic package focused on this (geomtextpath) I'm closing this
