### ISSUE TITLE
geom_circle() fails if aes(x = [something],  y=[something_else]) is included.

### ISSUE THREAD

**Issue by steenharsted** [thomasp85/ggforce#148]
Hi, 
Thank you for your many great packages!

I think there is a bug in geom_circle()
The error seems to come when if aes( x = [something], y = [something_else]) is included in the starting call to ggplot:

Library and data:

```
library(tidyverse)
library(ggforce)

person <- tribble(
  ~object,    ~x,    ~y,   ~group, ~size,
  "head",      100,   180,      1,    10, 
  "neck",      100,   160,      1,    3, 
  "pelvis",    100,   100,      1,    3, 
  "lhip",       90,    90,      2,    3, 
  "rhip",      110,    90,      3,    3,
  "lknee",      80,    45,      2,    3,
  "rknee",     120,    45,      3,    3, 
  "lfoot",      50,     0,      2,    3, 
  "rfoot",      150,    0,      3,    3,
  "lshoulder",   85,  155,      4,    3, 
  "rshoulder",  115,  155,      5,    3, 
  "lhand",      75,   100,      4,    3, 
  "rhand",      125,  100,      5,    3)
```

This works:
```
plot_x_y_aes_below <- ggplot(person, aes(x0=x, y0=y, r=size, group=group, fill=factor(group), color=factor(group))) +
  geom_circle(fill = "black") +
  geom_point(aes(x,y))+
  geom_path(aes(x,y)) +
  coord_equal() + 
  labs(x="cm", y="cm") + 
  theme_classic() +
  theme(legend.position = "none")

plot_x_y_aes_below
```
![image](https://user-images.githubusercontent.com/40394828/59256448-437d8b80-8c34-11e9-8a4a-9fecd4525ba8.png)

If we move aes(x,y) from geom_point and geom_path to the top:
```
plot_x_y_aes_on_top <- ggplot(person, aes(x = x, y = y, x0=x, y0=y, r=size, group=group, fill=factor(group), color=factor(group))) +
  geom_circle(fill = "black") +
  geom_point()+
  geom_path() +
  coord_equal() + 
  labs(x="cm", y="cm") + 
  theme_classic() +
  theme(legend.position = "none")

plot_x_y_aes_on_top
```
![image](https://user-images.githubusercontent.com/40394828/59256521-6dcf4900-8c34-11e9-94c1-9e6b927c2e9b.png)

Having played around with this I think the error is that the data becomes distorted (by a factor of ~2.5), and the "r" argument is ignored so the circle size becomes minimal. 
This becomes more clear if we manually override the r argument by setting the size argument.
*Perhaps also of interest, the fill argument is ignored, it is behaving like a point*
```
plot_x_y_aes_on_top_manuel_size <- ggplot(person, aes(x = x, y = y, x0=x, y0=y, r=size, group=group, fill=factor(group), color=factor(group))) +
  geom_circle(fill = "black", size = 5) +
  geom_point()+
  geom_path() +
  coord_equal() + 
  labs(x="cm", y="cm") + 
  theme_classic() +
  theme(legend.position = "none")

plot_x_y_aes_on_top_manuel_size
```
![image](https://user-images.githubusercontent.com/40394828/59256889-2c8b6900-8c35-11e9-9f07-ae3fba1d71ea.png)

If I remove the geom_poin() the error is the same (see below). I therefore think the error comes from placing aes(x = [something], y = [something_else]) in the first call to ggplot.

```
plot_x_y_aes_on_top_manuel_size_no_geom_point <- ggplot(person, aes(x = x, y = y, x0=x, y0=y, r=size, group=group, fill=factor(group), color=factor(group))) +
  geom_circle(fill = "black", size = 5) +
  geom_path() +
  coord_equal() + 
  labs(x="cm", y="cm") + 
  theme_classic() +
  theme(legend.position = "none")

plot_x_y_aes_on_top_manuel_size_no_geom_point
```
![image](https://user-images.githubusercontent.com/40394828/59257091-90159680-8c35-11e9-9d0b-51ef7cb8e1bc.png)

I hope this can help.

**Comment by steenharsted** [comment]
This issue is unchanged and therefore still remains in version 0.3.0

**Comment by thomasp85** [comment]
Damn - should have tested 😕
