### ISSUE TITLE
Add geom_bar_arc() feature to another plot

### ISSUE THREAD

**Issue by TseWue** [thomasp85/ggforce#152]
Dear Thomas,

Thank you so much for your force and what you do with it - ggforce is one of the best things I encountered in R so far! I would like to use geom_bar_arc() as an annotation tool since I need round shapes and neither geom_rect() nor geom_segment() fulfill my needs. I have a donut plot (created with sunburst() from ggsunburst package) and as the outermost layer I would like to have 3 arcs to annotate the donut plot.

data.frame for sunburst plot
```
df_size <- read.table(header=FALSE, text = "
parent,node,timepoint,size
controls,normal,3.5h,100.00
controls,normal,24h,88.23
controls,SCV,24h,11.76
controls,normal,48h,72.09
controls,SCV,48h,27.91
samples,SCV,48h,36.04
samples,normal,48h,64.00
samples,SCV,24h,33.02
samples,normal,24h,67.00
samples,normal,3.5h,100.00")
```

data.frame for arcs
```
tp <- data.frame(
  time_point = c('3.5h', '24h', '48h', '24h'),
  start = c(5.235988, 1.047198, 2.094395, 4.18879),
  end = c(1.047198, 2.094395, 4.18879, 5.235988),
  stringsAsFactors = FALSE)
```
create sunburst plot featuring geom_arc_bar()
```
write.table(df_size,"df_size.csv", col.names = F, row.names = F, sep=",")
sb_size <- sunburst_data("df_size.csv", type="node_parent", sep=",", node_attributes = c("timepoint", "size"))
sunburst(sb_size, leaf_labels = F, node_labels = T, node_labels.min = 70, rects.fill.aes = "name") +
  scale_fill_discrete(guide=F) +
  geom_text(data = sb_size$leaf_labels, aes(x=x, y=y, label=paste(timepoint, size, sep="\n"))) +
  geom_arc_bar(aes(x0 =0, y0 =12, r0 =1, r = 3, start=start, end=end, fill = time_point), data = tp)
```
With the code above I get the following:
![grafik](https://user-images.githubusercontent.com/45228113/60653022-843e7e00-9e49-11e9-92d1-84aaaa3e9851.png)
I would like to have the arcs around the plot to better visualize the 3 timepoints 3.5h, 24h and 48h. I do get both plots but somehow I am missing the 3.5h arc and I don't manage to set the coordinates right. There is no negative y0 coordinate and also, the arcs do not form a proper circle. Do you know 
a) how I get my 5.235988 to 1.047198 radians arc back?
b) how I can set the coordinates for the geom_arc_bar() to fall around the donut plot AND make it properly circular?
c) how to make the geom_arc_bar() coordinates independent from the sunburst coordinates?

Question c) is because the plot looks like this when I comment the geom_arc_bar() line out.
![plot_zoom_1](https://user-images.githubusercontent.com/45228113/60653325-1e9ec180-9e4a-11e9-984d-5c103f858366.png)
So here the issue is that the rescaling of the sunburst plot is difficult once I add the geom_arc_bar() layer. In the plot above, you also see that the arcs squeeze into the sunburst plot, depending on the y0 value. 

### Thanks for your help!
May the force be with you,
Tse

`> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.5`

**Comment by thomasp85** [comment]
I'm afraid I know too little about how ggsunburst works... my guess is it is using a polar coordinate system which will mess up geom_arc_bar... perhaps you can try with the sunburst functionality in ggraph which is plotted in a standard cartesian coordination system
