### ISSUE TITLE
angle in geom_regon()

### ISSUE THREAD

**Issue by dmi3kno** [thomasp85/ggforce#154]
I am trying to draw a proper hex (for the sticker):

```r
 ggplot() +
   geom_regon(aes(x0 = 0.5, y0 = 0.5, sides = 6,
                  angle = 11, r = 0.4)) +
   coord_fixed()
```
![geom_regon_angle_11](https://user-images.githubusercontent.com/13419011/61979540-6bfaf280-aff4-11e9-8aa9-88a1d8d46f94.png)

it is slightly off, so I want to correct the angle just a little bit
```r
 ggplot() +
   geom_regon(aes(x0 = 0.5, y0 = 0.5, sides = 6,
                  angle = 11.5, r = 0.4)) +
   coord_fixed()
```
![geom_regon_angle_115](https://user-images.githubusercontent.com/13419011/61979569-803eef80-aff4-11e9-85da-fe4549a0ce6e.png)

This does not make any sense! Does that mean that `angle` aesthetic is not expecting real numbers?

**Comment by thomasp85** [comment]
Pretty sure angle is in radians?

**Comment by dmi3kno** [comment]
fair enough. Sorry!
