### ISSUE TITLE
Broken link to the vignette

### ISSUE THREAD

**Issue by matteodefelice** [thomasp85/ggforce#158]
Both on github and on the official website the link to the vignette is broken.

**Comment by bbolker** [comment]
I can see from the `NEWS` file that: "Removed the Visual Guide vignette to reduce compilation time. See the website for an overview of all functionality with compiled examples (https://ggforce.data-imaginist.com)" - but the web page still directs us to the vignette, as @matteodefelice points out.  Perhaps as an interim measure the vignette source could go somewhere in `inst` so we can access it via `system.file()` ?

**Comment by thomasp85** [comment]
The link has been changed as the vignette has been removed. It was only ever necessary when there wasn’t a webpage with examples and added a lot of time to check and build times

**Comment by bbolker** [comment]
I guess the point is that the web page presented *doesn't* seem to have many examples.

[This website](https://ggforce.data-imaginist.com/) says

> The package has a website where every feature is described and justified with examples and plots.

now the "website" link goes right back to https://ggforce.data-imaginist.com/ , which seems to be just the same as the README file.   Is there in fact a web page somewhere with examples?

**Comment by thomasp85** [comment]
Yeah, well the front page of the website is just the readme so following the link from the website is a bit circular... the webpage contains documentation for all functions along with compiled example code — don’t know what else you’d expect?

**Comment by bbolker** [comment]
OK, I guess I didn't see the "Reference" drop-down.  Sorry to bother you.  Maybe, for idiots like me, add a sentence that says "see the 'Reference' tab at the top of the page for a complete list of functions in the package, along with documentation and examples."

**Comment by thomasp85** [comment]
Sure, I guess it could be better worded🙂

**Comment by DanChaltiel** [comment]
For people like me who like articles/vignettes, you can find the old one on http://cran.nexr.com/web/packages/ggforce/vignettes/Visual_Guide.html (hoping it is not too outdated)

@thomasp85 Looking in Reference does not feel the same: in the vignette, I can see all the functions and their output without having to navigate through many redundant pages. If the compilation time is less of an issue than it was five years ago, maybe you can reconsider?
