### ISSUE TITLE
geom_mark_* with ggraph

### ISSUE THREAD

**Issue by dylanmr** [thomasp85/ggforce#159]
Hi Thomas,

Thank you for these wonderful additions to ggplot. I have been trying to get the geom_mark_* commands to interact with ggraph to highlight different communities, but i haven't been able to get this to work. Should these commands work seamlessly with one another or am I missing something?

Attached below is an example of my code:

``` r
library(ggraph)
#> Loading required package: ggplot2
library(igraph)
#> 
#> Attaching package: 'igraph'
#> The following objects are masked from 'package:stats':
#> 
#>     decompose, spectrum
#> The following object is masked from 'package:base':
#> 
#>     union
library(tidygraph)
#> 
#> Attaching package: 'tidygraph'
#> The following object is masked from 'package:igraph':
#> 
#>     groups
#> The following object is masked from 'package:stats':
#> 
#>     filter
library(ggforce)
graph <- graph_from_data_frame(highschool)
g<-as_tbl_graph(graph)
g %>% activate(nodes) %>%
  mutate(community = as.factor(group_edge_betweenness()))  -> g
# Not specifying the layout - defaults to "auto"
p1<-ggraph(g) + 
    geom_edge_link() + 
    geom_node_point(aes(fill=community, size=4), shape=21)
#> Using `nicely` as default layout
p1
```

![](https://i.imgur.com/oasJTKY.png)

``` r
p1 + geom_mark_ellipse(aes(fill=community))
#> Error: geom_mark_ellipse requires the following missing aesthetics: x, y
```

![](https://i.imgur.com/bidyxpx.png)

<sup>Created on 2019-08-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thomasp85** [comment]
They work fine together, but as it is not a ggraph geom you'll have to specify the x and y coordinates:

```r
p1 + geom_mark_hull(aes(x = x, y = y, fill = community))
```
![image](https://user-images.githubusercontent.com/1775316/62969955-afd06300-be0e-11e9-886b-0ef1be9ec03f.png)

**Comment by davidizquierdogomez** [comment]
Thanks for this information, but I have another question:

what if we wanted to set the colour of the nodes based on the column year of the g data frame?

I network with different color for geom_node_points and the geom_mark_hull

This is my guess but it does not work...

library(ggforce)
graph <- graph_from_data_frame(highschool)
g<-as_tbl_graph(graph)
g %>% activate(nodes) %>%
  mutate(community = as.factor(group_edge_betweenness()))  -> g
# Not specifying the layout - defaults to "auto"
p1<-ggraph(g) + 
    geom_edge_link() + 
    geom_node_point(aes(fill=year, size=4), shape=21)
#> Using `nicely` as default layout
p1 + geom_mark_hull(aes(x = x, y = y, fill = community))

**Comment by RiboRings** [comment]
Hi!

Is there any way to colour areas not by node but by edge type?
