### ISSUE TITLE
'facet_matrix' is not an exported object from 'namespace:ggforce'

### ISSUE THREAD

**Issue by elcansaito** [thomasp85/ggforce#162]
Hi there, 
Trying to run Facet_matrix with my PCA analysis. 
I normally load my packages like this.

packages <- c("tidyverse," "reshape2","superheat","gplots","igraph","ggforce","gganimate")
package.check <- lapply(packages, FUN = function(x) {
  if (!require(x, character.only = TRUE)) {
    install.packages(x, dependencies = TRUE)
    library(x, character.only = TRUE)
  }
})

WHEN I run the code below, it says "Error in facet_matrix(vars(columns)) : 
  could not find function "facet_matrix"

columns <- res.pca$x[,1:5]
ggplot(res.pca$x, aes(x = .panel_x, y = .panel_y)) + 
  geom_point(alpha = 0.2, shape = 16, size = 0.5) + 
  facet_matrix(vars(columns))

THEN I use geforce:facet_matrix to force to use the package, but then I got the error on the Issue title. ANY HELP, appreciate it? THANKS.

columns <- res.pca$x[,1:5]
ggplot(res.pca$x, aes(x = .panel_x, y = .panel_y)) + 
  geom_point(alpha = 0.2, shape = 16, size = 0.5) + 
  ggforce::facet_matrix(vars(columns))

**Comment by steenharsted** [comment]
Two things:
1) Can you make a reprex (reproducible example)? We don't have the data in `res.pca` or know the structure.

2) Are you sure you have the latest version of ggforce installed? ggforce::facet_matrix() seems to work fine on my computer.

Cheers.

**Comment by elcansaito** [comment]
Thanks steenharsted for your fast reply. I attached two files R.Data and the code.
I used devtools::install_github("thomasp85/ggforce") to be sure that it was the latest version. Same error. 


![Reprex RData](https://user-images.githubusercontent.com/8972010/63008627-dfb55000-be7a-11e9-9252-9c7592a85edc.jpeg)

![ReprexGithub R](https://user-images.githubusercontent.com/8972010/63008650-ed6ad580-be7a-11e9-859e-d991673950ed.jpeg)

**Comment by elcansaito** [comment]
It attached them as jpeg because I thought it come download it and change afterwards. 
Attached it now as a zip. 
THANKS
[Reprex.zip](https://github.com/thomasp85/ggforce/files/3500607/Reprex.zip)

**Comment by steenharsted** [comment]
Hi Elcansaito,

Thanks for the reprex. 

Can you please run `packageVersion("ggforce")` ?

When I run your code I get error messages as well, but they are different from yours.
The error messages I get comes from the fact that you are trying to facet over numerical columns which is not possible. I can help perhaps help you solve that problem later. 

For your immediate problem, I am almost sure that it is caused by you loading an earlier version of ggforce where the `facet_matrix()` function is not included (That would be any version earlier than 0.3.0).

If `packageVersion("ggforce")`  does not return 0.3.0 or higher you know what the problem is.

Cheers.

**Comment by elcansaito** [comment]
Thanks again steenharsted, appreciate your time to try to sort it out. 
Yes, I was expecting that mistake, I was playing to see how to fix it. 
I run the code and the version is 
> packageVersion("ggforce")
[1] ‘0.3.0.9000’

In fact, I wanted to use ggforce for the first time because I read this
https://www.data-imaginist.com/2019/a-flurry-of-facets/
and I love the graphing from ggforce on PCAs.

**Comment by steenharsted** [comment]
Hmm... I have no idea then what's causing those errors that you get. Can you give the output of `sessionInfo() ` ?

If I use your data to create a matrix-panel similar to the one in the blog I do the following:

```
library(tidyverse)
library(ggforce)

packageVersion("ggforce")

[1] ‘0.3.0’
```

```
res.pca2 %>% 
  as_tibble() %>% 
  select(1:5) %>%
  ggplot(aes(x = .panel_x, y = .panel_y)) + 
  geom_point(alpha = 0.2, shape = 16, size = 0.5) + 
  facet_matrix(vars(everything()))
```

![image](https://user-images.githubusercontent.com/40394828/63025529-aa742680-bea9-11e9-865a-0c0540f49fce.png)

**Comment by thomasp85** [comment]
This may be a stupid suggestion but have you restarted your r session?

**Comment by elcansaito** [comment]
Thanks steenharsted and thomasp85(there is no stupidity in uncertainty).

I have been investigating and I think the issue was with the history file in R.
I think the loading function might have been the reason after the masking of many packages. I clean the R history file, restart the Studio and did the analysis just loading tidy verse and ggforce and it worked!!!!.
Thanks a million for helping me on trying to figure it out!!!
J

**Comment by thomasp85** [comment]
Happy you got it to work
