### ISSUE TITLE
facet_grid_paginate gives error with space = "free_y"

### ISSUE THREAD

**Issue by filipamsmartins** [thomasp85/ggforce#170]
hi, I am trying to export my results using facet_grid_paginate but when I include space = "free_y" it gives the following error:
**Error in ranges[[i]] : subscript out of bounds**

the final layout i desire for my dataset is given by the command below, using a subset of the _diamonds_ dataset as example:
```
# Subset data
diamonds1 <- diamonds[diamonds$color %in% c("H","I","J") & diamonds$table %in% c(55:58),]
diamonds1 <- diamonds1[sample(nrow(diamonds1),200, replace=TRUE),]

# Calculate the number of rows
n_row <- length(unique(paste(diamonds1$color,diamonds1$clarity, sep = ":")))

# Export each page (pdf format)
pdf("diamonds_test.pdf", width=8, height=8)
for(i in 1:2){
print(ggplot(diamonds1) + 
  geom_point(aes(cut, carat), alpha = 0.1) + 
  coord_flip() +
  facet_grid_paginate(color + clarity ~ table, scales = "free_y", space = "free_y", switch="y",
                      ncol = 2, nrow = n_row, page = i) +
  theme(strip.text.y = element_text(face = "bold", angle = 180),
        strip.placement = "outside",
        axis.text.y = element_text(size = 7)))
}
dev.off()
```
could you provide me some assistance please?

i also would like to suggest that the function could have an extra option for the `ncol` or `nrow` settings (e.g. "complete" besides "null" and numeric values) so it calculates the value by itself whenever we only want to constrain one of them for the page number given. in the example above i had to calculate `nrow` beforehand.

Thank you in advance

**Comment by bmplaw** [comment]
Im also getting errors with space = "free". I would appreciate if anyone knows a solution.

**Comment by thomasp85** [comment]
This appears to be solved - please reopen if the issue remains
