### ISSUE TITLE
ggforce::geom_link2 unexpected behavior with more than two toned color scales

### ISSUE THREAD

**Issue by EvaMaeRey** [thomasp85/ggforce#173]
tibble(x = 1:12, y = rep(0:3, 3)) %>% 
  ggplot() +
  aes(x = x) +
  aes(y = y) +
  aes(col = y) +
  geom_point() +
  scale_color_viridis_c() +
  ggforce::geom_link2() 

geom_link2 is cool! I was a little surprised by the behavior for this example.  I thought the color would map from the viridis scale based on the interpolated y position, but instead the color is interpolated from the color at the two end points.  I wonder if there should be different behavior for continuous or discrete variable mapped to color.  Thanks!

**Comment by thomasp85** [comment]
It does what it is supposed to do. It will map the aesthetics of the provided points and interpolate between these. What you ask is quite different, but potentially also useful - I'll consider it for a new feature

**Comment by EvaMaeRey** [comment]
Great!  Thanks!
