### ISSUE TITLE
facet_zoom not working with ggmap

### ISSUE THREAD

**Issue by PetoLau** [thomasp85/ggforce#177]
Hi,

I have an issue with combining ggmap with facet_zoom, it's not zooming...

`library(osmdata)
library(ggmap)
library(ggforce)`

`ba_bb <- getbb(place_name = "Bratislava")`
 `map_of_ba <- get_map(location = ba_bb, source = 'osm')`

 `ggmap(map_of_ba) +
   facet_zoom(xlim = c(17.07213,17.13245),
              ylim = c(48.13586, 48.17451),
              horizontal = FALSE, zoom.size = 0.5
   )`

![plot_zoom_png](https://user-images.githubusercontent.com/8727028/67580747-2363ea00-f747-11e9-9306-08843aa6fc0d.png)

**Comment by thomasp85** [comment]
I'm afraid ggmap does not behave like a standard ggplot2 extension so it is not possible for me to interface with it in general.
