### ISSUE TITLE
geom_circle - alpha setting does not affect the black perimeter circle

### ISSUE THREAD

**Issue by steenharsted** [thomasp85/ggforce#180]
The surrounding circle in geom_circle is not affected by the alpha setting, and therefore retains an alpha value of 1.

Reprex:
``` r
library(ggforce)
#> Indlæser krævet pakke: ggplot2

df <- data.frame(
  x = seq(1:10),
  y = seq(1:10),
  z = seq(0.1, 1, by = 0.1 ))

ggplot(df, aes(x0 = x, y0 = y, alpha = z))+
  geom_circle(aes(r = 0.6), fill = "blue")
```

![](https://i.imgur.com/dJgS2In.png)

``` r


# Equivalent using geom_point, please notice the alpha of the black perimeter line
ggplot(df, aes(x = x, y = y, alpha = z))+
  geom_point(size = 10, fill = "blue", shape = 21)
```

![](https://i.imgur.com/LwvYeaE.png)

<sup>Created on 2019-11-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thomasp85** [comment]
Yeah, that is standard behaviour for polygons in ggplot2. The next ggplot2 release will have some utilities for overwriting this
