### ISSUE TITLE
Use linear_trans() within ggplot call?

### ISSUE THREAD

**Issue by willgearty** [thomasp85/ggforce#181]
Is there any way to use `linear_trans()` within a ggplot call like you can with `power_trans()`?

**Comment by thomasp85** [comment]
No - it is meant for transformations outside of scales

**Comment by willgearty** [comment]
For anyone that finds this issue, I've made a custom coord that can transform data based on the results of `linear_trans()` in my package here: https://github.com/willgearty/deeptime
