### ISSUE TITLE
Problem  with facet_grid_paginate() 

### ISSUE THREAD

**Issue by rolfTurner** [thomasp85/ggforce#183]
I am trying to produce a ggplot2 graphic in which there is a single conditioning variable with a large number of levels (24).

If I use facet_grid() I get a plot with either 24 rows or 24 columns,
both of which look like hell.

I thought that facet_grid_paginate() would rescue me, but it doesn't seem to.  I asked for 3 rows and 4 columns, and thought that I would get two 3 x 4 pages  Instead I get six pages with only one row (of four facets) per page.

Am I misunderstanding something?  Making some silly syntactical error?  Or is this a bug?

I have attached a reproducible example, along with the data set on which it depends.

Grateful for any insight.

P.S.  Someone suggested to me that I could use facet_wrap() from ggplot2 instead. I got this to work for the example in question, but it requires manually subsetting the data so as to get one page at a time.  It's not clear to me how to do this in the general context in which I need to implement this procedure.  I'm hoping that facet_grid_paginate() will handle this for me automagically.

[reprex.txt](https://github.com/thomasp85/ggforce/files/3908762/reprex.txt)
[egDat.txt](https://github.com/thomasp85/ggforce/files/3908764/egDat.txt)

**Comment by annikaputt** [comment]
This is an old post, but I also ran into this issue. facet_grid() and facet_wrap() behave differently and require different inputs. In this situation you want facet_wrap_paginate() since you are only faceting across one variable.
