### ISSUE TITLE
Feature Request: Allow adding of `facet_wrap_paginate()` or `facet_grid_paginate()` more than once replacing existing arguments

### ISSUE THREAD

**Issue by billdenney** [thomasp85/ggforce#184]
To help with an issue similar to the first in #7, it would be helpful if a plot could be updated with a new addition of `facet_wrap_paginate()` which could only be used to select the page of interest such as the following:

``` r
library(ggplot2)
library(ggforce)
p <-
  ggplot(diamonds, aes(x=carat, y=price)) +
  geom_hex() +
  facet_wrap_paginate(facets="color", nrow=1, ncol=1)

p + facet_wrap_paginate(page=1)
#> Error in facet_wrap(facets, nrow = nrow, ncol = ncol, scales = scales, : argument "facets" is missing, with no default
```

<sup>Created on 2019-12-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thomasp85** [comment]
I agree that this would be nice, but it is not something ggforce have control over, as facet addition is handled by ggplot2
