### ISSUE TITLE
Feature Request: Allow page indexing for `facet_wrap_paginate()` and `facet_grid_paginate()` by facet name

### ISSUE THREAD

**Issue by billdenney** [thomasp85/ggforce#185]
This is tangentially related to #184 (I'm using a nearly identical example for how I'd like to be able to print).

Sometimes, I will know the specific page(s) of interest that I want to print by the value of the faceting variable(s).  It would be helpful to have the ability to index to a specific page by name as in the following example.  I acknowledge that it gets more complicated when there is more than one facet level, and for that, I assume that it will depend on the internal structure of how the pages are stored, but perhaps a vector of names like the second example would be reasonable.

# Example 1

``` r
library(ggplot2)
library(ggforce)
p <-
  ggplot(diamonds, aes(x=carat, y=price)) +
  geom_hex() +
  facet_wrap_paginate(facets="color", nrow=1, ncol=1)

p + facet_wrap_paginate(page="D")
#> Error in facet_wrap(facets, nrow = nrow, ncol = ncol, scales = scales, : argument "facets" is missing, with no default
```

<sup>Created on 2019-12-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

# Example 2

``` r
library(ggplot2)
library(ggforce)
p <-
  ggplot(diamonds, aes(x=carat, y=price)) +
  geom_hex() +
  facet_wrap_paginate(facets=c("color", "clarity"), nrow=1, ncol=1)

p + facet_wrap_paginate(page=c("D", "I1"))
#> Error in facet_wrap(facets, nrow = nrow, ncol = ncol, scales = scales, : argument "facets" is missing, with no default
```

<sup>Created on 2019-12-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thomasp85** [comment]
This seems to only address faceting with a single panel per page... I'm reluctant to add something with such a narrow scope

**Comment by billdenney** [comment]
In my case, the single panel method is a common need.  But, I can imagine a ways that it could be extended to cover multiple panels per page:

If you request the page containing "D", you get the page that contains "D" and all the other panels that are on that page.  I acknowledge that this is only moderately useful as the user would have to know the separation of pages.  If multiple pages contain "D", then the first of those is returned (or more likely, that is an error because multiple facet values should have been provided).

If it still doesn't seem like a good fit, no worries to close this.

**Comment by thomasp85** [comment]
I do see the value of this but as I don't have any time to think of a way to implement it I'm closing it
