### ISSUE TITLE
feature request: geom_arc_bar with categorical axis

### ISSUE THREAD

**Issue by romainFr** [thomasp85/ggforce#189]
For now `geom_arc_bar` only understands x0 and y0 as numeric (on a continuous axis). Would it be too strange to have it working with categorical axis?
Minimum example:

```r
catpie <- data.frame(x=c("A","B","A","C"),y=c("1","2","2","1"),v1=c(0.5,0.8,0.6,1))
ggplot(catpie) + geom_arc_bar(aes(x0=x,y0=y,r0=0,r=0.5,amount=v1),stat="pie") + scale_x_discrete()

Error: Discrete value supplied to continuous scale
In addition: Warning messages:
1: In Ops.factor(paths$x, paths$x0) : ‘+’ not meaningful for factors
2: In Ops.factor(paths$y, paths$y0) : ‘+’ not meaningful for factors
```
And thanks for all the great work !

**Comment by thomasp85** [comment]
I wouldn't really know how to interpret a discrete scale in the context of an arc... arcs exist in 2D Euclidean space and thus requires two numerical dimensions to make sense

**Comment by funnell** [comment]
@thomasp85 wouldn't the ordered discrete axis elements just be mapped to a numerical scale, practically?
For what it's worth, I'd also love to be able to provide categorical variables to set x and y positions of arcs.
