### ISSUE TITLE
Smart text labels

### ISSUE THREAD

**Issue by clauswilke** [thomasp85/ggforce#199]
I'm considering writing a geom that can place text labels outside or inside bars, depending on whether there is space. I.e., it would do something like the following, but automatically:

``` r
library(ggplot2)

df <- data.frame(x = c(10000, 2000, 500), y = letters[3:1])

ggplot(df, aes(x, y)) + 
  geom_col() +
  geom_text(
    aes(label = x), size = 10,
    hjust = c(1, 1, 0),
    color = c("white", "white", "black")
  )
```

![](https://i.imgur.com/BPrJN3F.png)

<sup>Created on 2020-04-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Would you accept this as a PR? And how should it be called? `geom_smart_text()`? `geom_dynamic_text()`?

**Comment by thomasp85** [comment]
I would. Your naming idea is as good as mine, but maybe `geom_bar_label` since it is specifically made for that?

**Comment by clauswilke** [comment]
Yeah, maybe that's a good idea. And we could also add a `geom_col_label()` that goes with `geom_col()` (only difference would be the default stat).

**Comment by thomasp85** [comment]
@clauswilke should I close this?

**Comment by clauswilke** [comment]
Yes, please close. Never got around to it.
