### ISSUE TITLE
add median line to sina plot

### ISSUE THREAD

**Issue by crazyhottommy** [thomasp85/ggforce#20]
Hi,

`geom_sina()` is a good alternative to `geom_boxplot()`, how can I add the median line to sina plot as boxplot does?

I know I can lay over boxplot over it
`ggplot(df, aes(Distribution, Value))  + geom_violin(aes(fill = Distribution)) + geom_boxplot()`

or add a summary, but only using a point:

`stat_summary(fun.y=median, geom="point", fill= "white", shape = 21, size =2.5)`
what if I just want a short median line ?

Thanks very much,
Tommy

**Comment by thomasp85** [comment]
A quick thought would be to use `geom_errorbar` but with median as both the upper and lower summary function. This is not an ideal solution, but should work for most cases...

**Comment by crazyhottommy** [comment]
Thanks, I managed to make it work http://rpubs.com/crazyhottommy/sina-plot

**Comment by glocke01** [comment]
Since I found this via google, I'm going to add that the solution I recommend **crossbar**
`stat_summary(fun.y=median, geom="crossbar")`
