### ISSUE TITLE
nudge_x and nudge_y parameters in ggforce::geom_mark_rect()?

### ISSUE THREAD

**Issue by gorkang** [thomasp85/ggforce#209]
I am using the wonderful ggforce package to plot overlays with labels and everything works great, but I am really missing the `nudge_x`, `nudge_y` parameters that are found in `ggrepel::geom_label_repel()`

An example of the issue I am finding can be seen below. I am using  [BayesianReasoning](https://cran.r-project.org/web/packages/BayesianReasoning/index.html), a package to help understand how to interpret medical tests results (it uses ggforce::geom_mark_rect() for the overlays and their labels). 

If you use the code below, you will see a plot similar to Figure 1. The final position of the labels will depend on the resolution of your plot. **The issue with this plot is that the labels are all over the place (some on top, others at the bottom, others to the left)**.

``` r
# install.packages("BayesianReasoning")
library(BayesianReasoning)

PPV_heatmap(Min_Prevalence = 1, Max_Prevalence = 1200, Sensitivity = 81, Max_FP = 5,
            label_subtitle = "Prenatal screening for Down Syndrome by Age",
            overlay = "line",
            overlay_labels = c("40 y.o.", "35 y.o.", "30 y.o.", "25 y.o.", "20 y.o."),
            overlay_position_FP = c(4.8, 4.8, 4.8, 4.8, 4.8),
            overlay_prevalence_1 = c(1, 1, 1, 1, 1),
            overlay_prevalence_2 = c(68, 249, 626, 946, 1068))
```

Figure 1
![Rplot](https://user-images.githubusercontent.com/6491790/87077212-ce8ed380-c1f0-11ea-8edd-ff6475d6d5ab.png)

## Desired result

I would love to be able to use a `nudge_x` parameter in ggforce::geom_mark_rect() to give a more consistent look. In the example below (see Figure 2) nudging all the labels to the left.

Figure 2
![Rplot02](https://user-images.githubusercontent.com/6491790/87141647-5f0cf880-c271-11ea-9b63-662694ad11a8.png)

Thanks!

**Comment by thomasp85** [comment]
You can now anchor the labels using the x0 and y0 aesthetics. You can also choose to anchor only one of them and let the algorithm figure out the other
