### ISSUE TITLE
geom_mark_ellipse wrong angles in some cases

### ISSUE THREAD

**Issue by mcanouil** [thomasp85/ggforce#214]
Hi Thomas,

I am currently using ggforce v0.3.2 from CRAN (and ggplot2 v3.3.2) and encountered the same incorrect angle of the ellipses using `geom_mark_ellipse()`, although only for few cases in the following example.

``` r
dta <- structure(
  list(
    grp = structure(
      c(3L, 3L, 3L, 3L, 4L, 4L, 4L, 4L, 5L, 5L, 5L, 5L, 1L, 1L, 2L, 2L, 6L, 6L, 7L, 8L, 8L, 9L, 9L), 
      .Label = c("A", "B", "C", "D", "E", "F", "G", "H", "I"), 
      class = "factor"
    ), 
    x = c(
      -0.438074338255999, -0.370767494460568, 0.150527292726277, 0.095808687540943, 
      -0.31870129010178, -0.27795044795183, 0.410106828449667, 0.433669644997126, 
      -0.377028103665088, -0.49438202367048, 0.052679265482348, 0.0174187261847797, 
      -0.0960886246323784, 0.00558249462378787, -0.0617408158533575, 0.199816274983803, 
      -0.110432255817778, 0.457169456719158, 0.0126283456381771, 0.17348134038417, 
      0.491905329005678, -0.285398109745977, 0.329769817419319
    ), 
    y = c(
      -0.269514027427553, -0.310831727549581, -0.395431128518186, -0.388978076428911, 
      0.388720270480408, 0.327766968392974, 0.117980213299302, 0.0772582449746059, 
      -0.0812027023307243, 0.0121449546406414, -0.271276768662407, -0.257696720321687, 
      -0.0387237433397669, -0.0976179030062904, 0.105396346278391, 0.116204038271639, 
      0.333590356291615, 0.104541672304312, 0.237247845830021, -0.117846298195026, 
      0.0550496311549874, 0.270185593843908, 0.0830329600173245
    )
  ), 
  class = "data.frame", 
  row.names = c(NA, -23L)
)

library(ggplot2)
library(ggforce)
ggplot(
  data = dta,
  mapping = aes(x = x, y = y, colour = grp)
) +
  geom_point(na.rm = TRUE) +
  geom_mark_ellipse()
```

![](https://i.imgur.com/mFRi5Cy.png)

``` r

ggplot(
  data = subset(dta, grp %in% c("A", "F", "I")),
  mapping = aes(x = x, y = y, colour = grp)
) +
  geom_point() +
  geom_mark_ellipse()
```

![](https://i.imgur.com/GnqHECt.png)

_Originally posted by @mcanouil in https://github.com/thomasp85/ggforce/issues/120#issuecomment-688977541_

**Comment by py9mrg** [comment]
For me, I have found it doesn't like it when there are only 2 points in a group. But it's not exactly consistent as sometimes they're fine and sometimes not, but I can't work out the causal factor(s). Maybe something to do with how it is calculating angles and getting pi/2 out due to one of the trigonometric functions that presumably are used (if you imagine rotating your ellipses by 45 degrees then they'll be correct).

**Comment by mcanouil** [comment]
The fix is most likely either in the C++ code https://github.com/thomasp85/ggforce/blob/master/src/ellipseEnclose.cpp ( or maybe in the R code around https://github.com/thomasp85/ggforce/blob/master/R/mark_ellipse.R#L295-L327)
Although, I am not really familiar with grid objects (or C++).

**Comment by regenernate** [comment]
I'm still seeing this bug after pulling both the specific commit where you closed this issue and @HEAD. You can see it in the group at lower left of the attached image.

[pc1_x_pc2_Clusters_008.pdf](https://github.com/thomasp85/ggforce/files/9577049/pc1_x_pc2_Clusters_008.pdf)

**Comment by thomasp85** [comment]
Can you provide a reprex that shows the bug, since the one shared above has been fixed?

**Comment by regenernate** [comment]
I could, but it turns out that RStudio was sourcing the wrong version of ggforce. You are correct that this issue is resolved. Thanks for the quick response.

**Comment by thomasp85** [comment]
all good - glad it is fixed

**Comment by SotiriosVasileiadis** [comment]
This issue seems to be recurring at MacOS (Sequoia 15.6.1, at M4 Pro) running R v4.5.1 (tried also previous versions for arm64), even with more than two points per group and seems to be happening at a random manner. It does not happen at Ubuntu 24.04 or Ubuntu 22.04, and did not happen at my previous intel Mac. I provide two example plots here, one with only one ellipse being a reflection of its intended form and another with all of the ellipses being reflections.
Single ellipse being problematic:
[2_location_RDA_ggplot2.pdf](https://github.com/user-attachments/files/22878326/2_location_RDA_ggplot2.pdf)

Multiple ellipses being problematic:
[2_season_RDA_ggplot2.pdf](https://github.com/user-attachments/files/22878333/2_season_RDA_ggplot2.pdf)

Any suggestions for solving this issue are totally appreciated!

**Comment by julianzaugg** [comment]
Hi @thomasp85 I am also experiencing the exact same issue as described by @SotiriosVasileiadis (MacOS Sequoia `15.7`, R ver `4.5.1`, ggforce ver. `0.5.0`). Multiple (>2) points in a group, but ellipses are the wrong angle for some of the groups.

**Comment by mcanouil** [comment]
If you want a fix, providing a small fully reproducible example is required.

**Comment by julianzaugg** [comment]
@mcanouil I can trigger the issue using the example from [issue #299](https://github.com/thomasp85/ggforce/issues/299#issue-1627290090):

```
library(tidyverse)
library(ggforce)

test_dataset <- tibble(x     = c(-235, -220,  187, -100, -162,   8, 336, 159, 443, -77, -412), 
                       y     = c( -32, -147, -123,    6,  102, -14,  40,   6,  15, 115,   30),
                       group = c( "a",  "a",  "a",  "b",  "b", "b", "c", "c", "c", "d",  "d"))

ggplot(test_dataset, aes(x = x, y = y, fill = group)) + 
  geom_mark_ellipse() +
  geom_point(shape = 21, size = 3, color = "black")
```

<img width="823" height="603" alt="Image" src="https://github.com/user-attachments/assets/d7be84f3-041c-43e7-b155-78cccf6d46f6" />

**Comment by gruensch** [comment]
> [@mcanouil](https://github.com/mcanouil) I can trigger the issue using the example from [issue #299](https://github.com/thomasp85/ggforce/issues/299#issue-1627290090):
> 
> ```
> library(tidyverse)
> library(ggforce)
> 
> test_dataset <- tibble(x     = c(-235, -220,  187, -100, -162,   8, 336, 159, 443, -77, -412), 
>                        y     = c( -32, -147, -123,    6,  102, -14,  40,   6,  15, 115,   30),
>                        group = c( "a",  "a",  "a",  "b",  "b", "b", "c", "c", "c", "d",  "d"))
> 
> ggplot(test_dataset, aes(x = x, y = y, fill = group)) + 
>   geom_mark_ellipse() +
>   geom_point(shape = 21, size = 3, color = "black")
> ```
> 
> <img alt="Image" width="823" height="603" src="https://private-user-images.githubusercontent.com/672220/511245414-d7be84f3-041c-43e7-b155-78cccf6d46f6.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Njc5NDk4NDgsIm5iZiI6MTc2Nzk0OTU0OCwicGF0aCI6Ii82NzIyMjAvNTExMjQ1NDE0LWQ3YmU4NGYzLTA0MWMtNDNlNy1iMTU1LTc4Y2NjZjZkNDZmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDEwOVQwOTA1NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jODE1M2YwNTI1ZjgxMWM2NTdhNjQwZTQxMmM4MzdhMDE1OTQzZjFjNGMwMWU5YWI2Y2I1YmI2NmJiMzc3MWNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TGW7TOy828PBvx7Cw2znyLTVusI93EkZ1wu3LJ2gTRs">

the issue is still occurring using the same example above under 
R version 4.5.2 (2025-10-31)
Platform: x86_64-pc-linux-gnu
Running under: Ubuntu 24.04.3 LTS
Package version ggforce_0.5.0.9000

**Comment by mcanouil** [comment]
It would be better to actually open a new issue referencing this one and telling it has regressed than commenting on a three years old issue that was really fixed at time.
Unfortunately, your comments is unlikely to get any traction on the issue.
