### ISSUE TITLE
facet_wrap_paginate - Error: Cannot create zero-length unit vector ("unit" subsetting)

### ISSUE THREAD

**Issue by pausoto7** [thomasp85/ggforce#215]
After updating R and its associated packages (ggforce, ggplot etc), facet_wrap_paginate no longer works when I only have one plot for the page. Previously having one plot and nrow =2, and ncol = 2 worked fine, but now when I do this I get "Error: Cannot create zero-length unit vector ("unit" subsetting)" . I found that I can have nrow = 2, but with any number greater than 1 for ncol the code breaks. I tested this with pages that have numerous plots and it works fine then. 

```{r working}
          p1 <-  Specific_TS %>%
            ggplot(aes(x=DateTime,y=summary_value)) +
            geom_point()+
            geom_line() +
            facet_wrap_paginate(clean_name~Location, nrow = 5, 
                                ncol = 5, 
                                page = pages)


         print(p1)

Error: Cannot create zero-length unit vector ("unit" subsetting)

```

**Comment by farhadsalimi** [comment]
Any update on this?

**Comment by billytheblock** [comment]
@farhadsalimi, I downloaded the ggforce package and modified facet_wrap_paginate.R based on [@crotoc's suggestion](https://github.com/crotoc/ggforce/commit/57a7da43cbaccea72ec96300bd89f673d3a4660e?branch=57a7da43cbaccea72ec96300bd89f673d3a4660e&diff=unified). I followed [these](https://stackoverflow.com/questions/34800331/r-modify-and-rebuild-package/34800599) instructions (for Linux Environment) to download, edit, rebuild, and reinstall the package. Seems to have solved the problem, at least for my specific needs.

**Comment by thomasp85** [comment]
This seems to be fixed in the latest versions
