### ISSUE TITLE
geom_spiro - edge correction for revolutions

### ISSUE THREAD

**Issue by pjt222** [thomasp85/ggforce#217]
Hi Thomas,

I am using ggforce_0.3.2 and ggplot2_3.3.2 and use geom_spiro. The created plots will result in an sharp edge at the starting and endpoint of the path. 

``` r,
ggplot() +
  geom_spiro(
    aes(
      R = 13,
      r = 3,
      d = 3,
      outer = TRUE
    )
  ) +
  theme_void()
```
[spiro_revo_null.pdf](https://github.com/thomasp85/ggforce/files/5523562/spiro_revo_null.pdf)

In contrast, setting the parameter `revolutions` to a value greater than the internally calculated `revo` will solve the issue.

```r,
ggplot() +
  geom_spiro(
    aes(
      R = 13,
      r = 3,
      d = 3,
      outer = TRUE
    ), 
    revolutions = 4 
  ) +
  theme_void()
```
[spiro_revo_4.pdf](https://github.com/thomasp85/ggforce/files/5523575/spiro_revo_4.pdf)

Therefore, I suggest that changing the default behaviour of geom_spiro, in terms of calculating 'revo', could be of help.

```r,
if (is.null(revolutions)) {
      revo <- attr(fractions(data$r / data$R), 'fracs')
      revo <- as.numeric(sub('/.*$', '', revo))
      revo <- revo + 1
    }
```

Best regards, Philipp

**Comment by thomasp85** [comment]
Setting it higher would result in overplotting thus making e.g. `alpha` not look as intended. In your case you can get a round edge by setting `lineend = "round"`

**Comment by pjt222** [comment]
Hey Thomas, I agree with you. Thanks for pointing me to the `lineend` parameter. This works like a charm. Best regards, Philipp.
