### ISSUE TITLE
facet_zoom fails with geom_vline

### ISSUE THREAD

**Issue by brendanf** [thomasp85/ggforce#221]
```
library(ggplot2)
library(ggforce)

ggplot(iris, aes(Petal.Length, Petal.Width, colour = Species)) +
  geom_point() +
  geom_vline(xintercept = 4) +
  facet_zoom(xy = Species == 'versicolor')
```
`Error in scale_index[[i]] : subscript out of bounds`

Using ggforce 0.3.1 and ggplot2 3.2.1 in R 3.5.1, and also using ggforce 0.3.2 and ggplot2 3.3.3 in R 4.0.3.

**Comment by brendanf** [comment]
There is no problem if the zoom limits are explicitly given instead of calculated from the data:

```
ggplot(iris, aes(Petal.Length, Petal.Width, colour = Species)) +
  geom_point() +
  geom_vline(xintercept = 4) +
  facet_zoom(xlim = c(3, 5.2), ylim = c(1,1.8))
```

**Comment by krlmlr** [comment]
Same with `geom_hline(yintercept = )` .

**Comment by thomasp85** [comment]
Fixed in latest version
