### ISSUE TITLE
Issues Installing in RStudio Cloud

### ISSUE THREAD

**Issue by andreafederica** [thomasp85/ggforce#231]
Hello,

I teach High School level Intro to Data Science. One of our packages we use is ggforce, and ever since the 0.3.3 update, I'm not able to download this package using RStudio Cloud. It gives a super-long error message!

I've even tried using a brand-new project file just now, and I'm getting the same errors. It keeps giving warnings and errors about RcppEigen and packets. If you'd like, I can certainly copy/paste some of the error codes into here.

Thank you,

Andrea

**Comment by thomasp85** [comment]
if this is still an issue please provide me with the installation error so I can look into it

**Comment by andreafederica** [comment]
Oh, thanks for responding! No, I think I was able to solve this. Either way, I don't have this job anymore, so no worries.
-------- Messaggio originale --------Da: Thomas Lin Pedersen ***@***.***> Data: 31/08/22  07:02  (GMT-08:00) A: thomasp85/ggforce ***@***.***> Cc: andreafederica ***@***.***>, Author ***@***.***> Oggetto: Re: [thomasp85/ggforce] Issues Installing in RStudio Cloud (#231) 
if this is still an issue please provide me with the installation error so I can look into it
