### ISSUE TITLE
geom_spiro not animatable

### ISSUE THREAD

**Issue by will-r-chase** [thomasp85/ggforce#233]
This "pretty useless" geom probably isn't at the top of the list of bugs to fix, but I thought I would put it out there that I can't get geom_spiro from ggforce to animate. Tried transition_time, transition_components, and transition_states but all three throw the error:
`Error in mapply(FUN = f, ..., SIMPLIFY = FALSE) : 
  zero-length inputs cannot be mixed with those of non-zero length`

Seems to be related to thomasp85/gganimate#139 and thomasp85/gganimate#196, probably geom_spiro is overwriting the group aesthetic which makes gganimate mad. 

Here's a reprex

```
library(ggplot2)
library(ggforce)
library(gganimate)

data <- data.frame(R = c(2, 3), r = c(1, 1), d = c(3, 2), id = c(1, 2))

#works
p <-
  ggplot(data) +
  geom_spiro(aes(R = R, r = r, d = d, group = id))

#doesnt work
p + transition_time(time = id)
p + transition_components(time = id)
p + transition_states(states = id)
```

**Comment by thomasp85** [comment]
This should work now
