### ISSUE TITLE
geom_circle is highly resource intensive

### ISSUE THREAD

**Issue by yhoogstrate** [thomasp85/ggforce#245]
I tried to make a corrplot like figure using `ggforce::geom_circle` using ~100 * 100 circles. This takes exceptionally long and consumes a lot of memory. I also noticed that when exporting a circles to vector format, the circles created consist of 360 individual connected points rather than an actual circle. This might be related to the issue.

I noticed that in another implementation of ,geom_circle, `geomnet::geom_circle`, (https://github.com/sctyner/geomnet/blob/master/R/geom-circle.r) actual circles are exported.

**Comment by thomasp85** [comment]
Yes, the whole point of `geom_circle()` is to calculate points along the periphery so the circle is scaled by the coordinate system. You can use the `n` argument to control how many points each circle should consist of
