### ISSUE TITLE
function 'Rcpp_precious_remove' not provided by package 'Rcpp'

### ISSUE THREAD

**Issue by hmutpw** [thomasp85/ggforce#246]
ata <- reshape2::melt(Titanic)
data <- gather_set_data(data, 1:4)

ggplot(data, aes(x, id = id, split = y, value = value)) +
  geom_parallel_sets(aes(fill = Sex), alpha = 0.3, axis.width = 0.1) +
  geom_parallel_sets_axes(axis.width = 0.1) +
  geom_parallel_sets_labels(colour = 'white')

Computation failed in `stat_parallel_sets()`:
function 'Rcpp_precious_remove' not provided by package 'Rcpp'

**Comment by thomasp85** [comment]
My guess is that you had a version mismatch in Rcpp and geforce. If the issue persists please reopen
