### ISSUE TITLE
`geom_mark_hull` does not work without an error message

### ISSUE THREAD

**Issue by su-park** [thomasp85/ggforce#247]
I installed `ggforce`, tried below codes and I got nothing **hulled**.

Actually there isn't any message why it does not work.

```
mpg %>%
  ggplot(aes(x = displ, y = hwy)) +
  geom_point() +
  geom_mark_hull(aes(filter = model == "corvette", label = model)) +
  labs(title = "Fuel economy from 1999 to 2008 for 38 car models",
       caption = "Source: https://fueleconomy.gov/",
       x = "Engine Displacement",
       y = "Miles per Gallon")
```

After some searches I noticed requirement for `concaveman` package.

you may need to add `concaveman` as a dependent package

**Comment by thomasp85** [comment]
I can't comment on why you didn't receive an error message. But the existence of concaveman is checked when using `geom_mark_hull()` and the user should be informed if it is missing
