### ISSUE TITLE
Use `facet_matrix`'s labels in `aes()`

### ISSUE THREAD

**Issue by mattansb** [thomasp85/ggforce#255]
I'd like the have shapes vary by the rows of a `facet_matrix`, is this possible? How does one access the x/y panel ID?

```R
library(ggplot2)
library(ggforce)

ggplot(mtcars) + 
  geom_point(aes(.panel_x, .panel_y)) + 
  facet_matrix(vars(mpg, cyl), vars(am, hp))

# How to have aes(shape = (.panel_x_var == "hp))?
```

**Comment by thomasp85** [comment]
There is a secret `PANEL` variable added to all data in R... while it is honestly not meant to be used like this it is there:

``` r
ggplot(mtcars) + 
    geom_point(aes(.panel_x, .panel_y, shape = factor(PANEL))) + 
    facet_matrix(vars(mpg, cyl), vars(am, hp))
```

![](https://i.imgur.com/yueL7Fn.png)

**Comment by thomasp85** [comment]
With some mathematics you should be able to target each row

**Comment by mattansb** [comment]
Oh that is some nice magic.

If anyone ever comes looking here...:

``` r
library(ggplot2)
library(ggforce)

p <- ggplot(mtcars) + 
  geom_point(aes(.panel_x, .panel_y)) + 
  facet_matrix(vars(mpg, am, cyl, carb), vars(am, cyl, hp))

factor_to_row <- function(f, nrow) {
  ncol <- max(as.numeric(f)) / nrow
  factor((as.numeric(f) - 1) %/% ncol)
}

factor_to_col <- function(f, ncol) {
  factor((as.numeric(f) - 1) %% ncol)
}

p + aes(shape = factor_to_row(PANEL, 4))
#> Warning in rows == cols: longer object length is not a multiple of shorter
#> object length
```

![](https://i.imgur.com/i8eSvyV.png)

``` r

p + aes(shape = factor_to_col(PANEL, 3))
#> Warning in rows == cols: longer object length is not a multiple of shorter
#> object length
```

![](https://i.imgur.com/7vdZ1r1.png)

<sup>Created on 2022-08-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by Pancreas-Pratik** [comment]
> There is a secret `PANEL` variable added to all data in R... while it is honestly not meant to be used like this it is there:
> 
> ```r
> ggplot(mtcars) + 
>     geom_point(aes(.panel_x, .panel_y, shape = factor(PANEL))) + 
>     facet_matrix(vars(mpg, cyl), vars(am, hp))
> ```
> 
> ![](https://camo.githubusercontent.com/2dcacfccbdb0241c2462cea03afea34889057ee9658e1529d32196c41b322132/68747470733a2f2f692e696d6775722e636f6d2f7975654c37466e2e706e67)

Yes!! This is everything I needed!
I've been struggling how to color specific plots within the plot grid conditionally. This will help me do this!

Please do not ever remove this @thomasp85 🙏🏾 I've been struggling for hours now, and this was the key I needed!
