### ISSUE TITLE
facet_zoom throws "subscript out of bounds" if x/y expressions include no data

### ISSUE THREAD

**Issue by ning-y** [thomasp85/ggforce#257]
```r
xs <- tibble(x=1:10, y=1:10)
ggplot(xs, aes(x=x, y=y)) + geom_point() + facet_zoom(x < 5)
# Obviously, this works.
ggplot(xs, aes(x=x, y=y)) + geom_point() + facet_zoom(x < 0)
# Error in scale_index[[i]] : subscript out of bounds
```

The `x < 0` in `facet_zoom` subsets no data, and this seems to throw an error.

The previous example is obviously trivial. But this error also appears when the facet_zoom x/y expression does subset from the full data as given in the ggplot call, but does not subset from an "overwriting" geom-specific data.

For example, suppose I want to label just outliers with geom_text.

```r
xs <- tibble(x=1:10, y=c(1:9, 100))
ggplot(xs, aes(x=x, y=y, label=y)) + 
  geom_point() + 
  geom_text(data=filter(xs, y > 50)) +
  facet_zoom(x<10)
# Error in scale_index[[i]] : subscript out of bounds

# But this works
ggplot(xs, aes(x=x, y=y, label=y)) + 
  geom_point() + 
  geom_text(data=filter(xs, y <= 50)) +
  facet_zoom(x<10)
```

For other users coming across this issue, one fix is to use xlim/ylim instead of x/y expressions (#221).

**Comment by thomasp85** [comment]
This seems to have been fixed in the latest dev version
