### ISSUE TITLE
Horizontal sina support

### ISSUE THREAD

**Issue by erikvona** [thomasp85/ggforce#263]
`geom_sina()` works fine if x is the categorical covariate, and y is numeric. However, if y is categorical and x is numeric, it fails, while we can still draw box/violin plots.

```r
library(ggforce)
ggplot(midwest, aes(state, area)) +
  geom_violin() +
  geom_sina()
# Works

ggplot(midwest, aes(area, state)) +
  geom_violin() +
  geom_sina()
# Warning messages:
# 1: In regularize.values(x, y, ties, missing(ties), na.rm = na.rm) :
#   collapsing to unique 'x' values
# 2: Computation failed in `stat_sina()`:
#   need at least two non-NA values to interpolate 
# Draws violin plot, but not sina plot
```

We can overcome this limitation by flipping plots with `coord_flip()`, however, it would be really nice if we didn't have to. Especially when working with multiple packages, it can be nice to specify x and y as you want them displayed, and not flipping the plot at the end.

Alternatively, we can use the ggbeeswarm package, which has a `groupOnX` parameter to determine whether to group on the X or Y axis, and can draw similar plots, but comes with a slightly different set of options.

**Comment by thomasp85** [comment]
This is now fixed in the dev version after adding bidirectional support
