### ISSUE TITLE
Not so much an issue, more a request, facet_nested_wrap?

### ISSUE THREAD

**Issue by gent-luke** [thomasp85/ggforce#270]
Hi! I really enjoy your package and I've used facet_wrap_paginate and facet_grid_paginate multiple times, was wondering is there a way facet_nested_wrap from the ggh4x package could be somehow inputed also? I'm not sure if what I'm asking is unorthodox or rude as I'm still quite new to all of this. Apologies if I've caused any offence or not noticed something obvious that can't be done!

**Comment by thomasp85** [comment]
Not rude at all :-)

I'm afraid such a feature is beyond what I would have time to look into at the moment
