### ISSUE TITLE
`geom_sina()` removes all data points when colouring by discrete variable

### ISSUE THREAD

**Issue by gl-eb** [thomasp85/ggforce#272]
I am trying to plot a small number of data points and colour them by a third variable. The x-axis as well as the colouring variable are discrete, while the y-axis is continuous. The reason I want to use `geom_sina()` is because the values can be almost identical, leading to overlapping points. I'd like the points to dodge, but only when their y value is similar. I know that `geom_beeswarm()` works, but development of ggbeeswarm has stagnated  and I'd like to explore other options.

This might be related to #268, since in my dataset every combination of `category` and `replicate` only has one data point.

What troubleshooting I've done:
- omitting `colour = replicate` results in the correct plotting of the points
- moving mapping to the `geom_sina()` function call (unsurprisingly) does not fix this issue
- using `geom_point()` instead of `geom_sina()` works as expected
- converting `replicate` to numeric fixes the issue, but now the colour scale is continuous instead of discrete (I'd like to use `scale_colour_manual()`)

Here's a reprex that closely mimics my conditions:
``` r
library(ggplot2)
library(ggforce)
library(tibble)

dat <- tibble(
  category = rep(c("A", "B", "C"), 3),
  value = 1:9,
  replicate = rep(1:3, each = 3)|> as.character()
)
dat
#> # A tibble: 9 × 3
#>   category value replicate
#>   <chr>    <int> <chr>    
#> 1 A            1 1        
#> 2 B            2 1        
#> 3 C            3 1        
#> 4 A            4 2        
#> 5 B            5 2        
#> 6 C            6 2        
#> 7 A            7 3        
#> 8 B            8 3        
#> 9 C            9 3

dat |> ggplot(aes(category, value, colour = replicate)) +
  geom_sina()
#> Warning: Removed 9 rows containing missing values (geom_point).
```

![](https://i.imgur.com/Jvf1qnl.png)

<sup>Created on 2022-08-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by thomasp85** [comment]
You will need to explicitly set the `group` aesthetic in `geom_sina()` since it will otherwise by the interaction between all categorical aesthetics (here, `category` and `replicate`)

```r 
dat |> ggplot(aes(category, value, colour = replicate)) +
    geom_sina(aes(group = category))
```
