### ISSUE TITLE
Error in `facet_zoom()` while using `theme_set()` and `ggthemes`

### ISSUE THREAD

**Issue by matiasandina** [thomasp85/ggforce#282]
I was trying to plot something using `facet_zoom()` with `xlim` to specify the region and was getting "subscript too long..." error. I tried the vanilla example from the docs and I got the same error.

``` r
library(ggplot2)
library(ggforce)
theme_set(ggthemes::theme_base() + theme(plot.background = element_rect(color=NA)))
ggplot(iris, aes(Petal.Length, Petal.Width, colour = Species)) +
  geom_point() +
  facet_zoom(xlim = c(2, 4))
#> Warning in rep(colour, length.out = length(alpha)): 'x' is NULL so the result
#> will be NULL
#> Error in `[<-`(`*tmp*`, !is.na(alpha), 4, value = alpha[!is.na(alpha)]): (subscript) logical subscript too long
```

I knew that the vanilla example had to work, so I tried it using `theme_gray()`  and it woks as expected.

```
# Works with theme gray()
ggplot(iris, aes(Petal.Length, Petal.Width, colour = Species)) +
  geom_point() + 
  theme_gray() +
  facet_zoom(xlim = c(2, 4)) 
```

![](https://i.imgur.com/ddXjniZ.png)

Same for `theme_bw()`

``` r
# Works with theme bw()
ggplot(iris, aes(Petal.Length, Petal.Width, colour = Species)) +
  geom_point() + 
  theme_bw() +
  facet_zoom(xlim = c(2, 4)) 
```

![](https://i.imgur.com/UtT1ajJ.png)

Not sure this is a `ggforce` or `ggthemes` issue to be honest, so this might not be the best place to put it.

<sup>Created on 2022-09-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by thomasp85** [comment]
This seems to be fixed. Feel free to reopen if it still causes an issue
