### ISSUE TITLE
R Compilation Failure

### ISSUE THREAD

**Issue by AdamPetrihos** [thomasp85/ggforce#284]
Hello,

I am unable to compile the ggforce package from source.

I am using an Apple M1 chip, and on R version 4.1.3

Below is my makeVars file, and the output from R.

MAKEVARS --------

FLIBS = -L/usr/local/gfortran/lib/gcc/aarch64-apple-darwin21/12.1.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lemutls_w -lm -lssl

openSSLLoc = /opt/homebrew/Cellar/openssl@1.1/1.1.1q

FC = /usr/local/gfortran/bin/gcc
F77 = /usr/local/gfortran/bin/gcc
CC = /usr/local/gfortran/bin/gcc

CXX = /usr/local/gfortran/bin/g++ -fopenmp
CXX11 = /usr/local/gfortran/bin/g++ -fopenmp
CXX14 = /usr/local/gfortran/bin/g++
CXX17 = /usr/local/gfortran/bin/g++
CXX20 = /usr/local/gfortran/bin/g++

CFLAGS = -g -O3 -Wall -I$(openSSLLoc)/include -L$(openSSLLoc)/lib
CXXFLAGS = -g -O3 -Wall -I$(openSSLLoc)/include -L$(openSSLLoc)/lib
LDFLAGS = -L/usr/local/lib -L$(openSSLLoc)/lib
CPPFLAGS = -I/usr/local/include -I$(openSSLLoc)/include

CONSOLE OUTPUT -------
* installing *source* package ‘ggforce’ ...
** package ‘ggforce’ successfully unpacked and MD5 sums checked
** using staged installation
** libs

ld: warning: -undefined dynamic_lookup may not work with chained fixups
ld: warning: dylib (/Library/Frameworks/R.framework/R) was built for newer macOS version (20.0) than being linked (12.5)
0  0x1010d81a0  __assert_rtn + 140
1  0x100f5fa8c  mach_o::relocatable::Parser<arm64>::parse(mach_o::relocatable::ParserOptions const&) + 4536
2  0x100f31d38  mach_o::relocatable::Parser<arm64>::parse(unsigned char const*, unsigned long long, char const*, long, ld::File::Ordinal, mach_o::relocatable::ParserOptions const&) + 148
3  0x100f9a4ac  ld::tool::InputFiles::makeFile(Options::FileInfo const&, bool) + 1468
4  0x100f9d360  ___ZN2ld4tool10InputFilesC2ER7Options_block_invoke + 56
5  0x1821301f4  _dispatch_client_callout2 + 20
6  0x182143954  _dispatch_apply_invoke + 224
7  0x1821301b4  _dispatch_client_callout + 20
8  0x182141a04  _dispatch_root_queue_drain + 680
9  0x182142104  _dispatch_worker_thread2 + 164
10  0x1822f0324  _pthread_wqthread + 228
A linker snapshot was created at:
	/tmp/ggforce.so-2022-09-27-134908.ld-snapshot
ld: Assertion failed: (_file->_atomsArrayCount == computedAtomCount && "more atoms allocated than expected"), function parse, file macho_relocatable_file.cpp, line 2061.
collect2: error: ld returned 1 exit status
make: *** [ggforce.so] Error 1
ERROR: compilation failed for package ‘ggforce’

**Comment by thomasp85** [comment]
Can you successfully compiler other packages that contains C++ code from source? None of the issues seems specific to ggforce at a glance
