### ISSUE TITLE
Possible issue with 'gather_set_data'?

### ISSUE THREAD

**Issue by mrossNSTG** [thomasp85/ggforce#285]
I had been using ggforce v0.3.2 for a while, but upgrading to v0.4.1 created different behavior in the _parallel sets_ functionality.
Originally, the 'gather_set_data' created an **x** column of repeated column headers of the data, which would translate into tidy x-axis tick labels in the final plot. with v.4.1, the function now produces an **x** column of repeated column numbers, and I cannot find how to rename these once set.
Below I've produced the 'Titanic' parallel sets, and note the tick labels 1 to 4:
![image](https://user-images.githubusercontent.com/68570881/198739033-da4ec646-16c3-45f4-8490-f4b01531bccb.png)
If I map back the column names to these numbers, the plot will not render.
data$x <- colnames(data)[data$x]
![image](https://user-images.githubusercontent.com/68570881/198739414-c43a5444-0897-4cc7-b0ac-03d193f7845e.png)
![image](https://user-images.githubusercontent.com/68570881/198739442-7243227d-63cb-439e-85df-84e2e671ebe3.png)

Thanks again for the really useful package!

**Comment by ycl6** [comment]
Hi @mrossNSTG 

I also observed this and provided a fix in #305. Maybe it'll help if you are still looking for a solution.
