### ISSUE TITLE
order of geom_circle does not hold

### ISSUE THREAD

**Issue by DSLituiev** [thomasp85/ggforce#296]
there seems to be a closed issue #224, but the @HEAD version still does not get this right:
 
```r
# none of these work:
# remotes::install_github("dmurdoch/ggforce@sortorder")
# remotes::install_github("thomasp85/ggforce")

set.seed(42)
tibble(size=1e-1 * 10^rnorm(10),
         x = rnorm(10),
         y = seq(1,10),
       fill = rbinom(10, 7, 0.2) %>% as.factor()
       ) %>% 
  arrange(-size) %>% 
  ggplot() +
  ggforce::geom_circle(aes(
    y0=y, x0=x, r=size, fill=fill,
    # order=y,
  ), colour = "black",
  ) + 
  geom_text(aes(x=x, y=y, label = y))
```

![image](https://user-images.githubusercontent.com/8426290/221654287-8f3f005a-66b6-4acf-b2cf-14d8b0c3ff67.png)

**Comment by thomasp85** [comment]
fixed

**Comment by thomasp85** [comment]
The reordering you see is because of the fill mapping which imposes a grouping which, in the end, influences the drawing order. This is a ggplot2 thing, not ggforce
