### ISSUE TITLE
Replacing concaveman

### ISSUE THREAD

**Issue by schochastics** [thomasp85/ggforce#308]
`concaveman` is just a suggested package, but it is quite heavy in terms of dependencies if it needs to be installed. 
There is potentially more lightweight option [RcppConcaveman](https://github.com/Jean-Romain/RcppConcaveman) which wraps a [C++](https://github.com/sadaszewski/concaveman-cpp) implementation of concaveman (unfortunatelly not on CRAN, but it seems quite easy to wrap the cpp code). It also comes with the added benefit of being more efficient.

**Comment by thomasp85** [comment]
Oh, nice - we should def explore this

**Comment by thomasp85** [comment]
hmmm... It appears that C++ port is severely bug-riddled as it misses points that ends up outside the hull, and makes up new points along the hull that was never there to begin with + it doesn't create the same result on multiple runs
