### ISSUE TITLE
stat_/geom_sina error with continuous x aesthetic

### ISSUE THREAD

**Issue by simonwmeng** [thomasp85/ggforce#35]
Occurs with both v0.1.0 and the master branch.

Minimal example:

```R
library(ggplot2)

library(ggforce)

df <- data.frame(
    x = rep(1:10, each = 100),
    y = rnorm(10000)
)
```

```R
ggplot(df, aes(x = factor(x), y = y)) + geom_sina()
```

Works.

```R
ggplot(df, aes(x = x, y = y)) + geom_sina()
```

Produces the following error instead of complaining about a continuous x aesthetic: `Error in f(...) : could not find function "has_groups"`.

**Comment by thomasp85** [comment]
I'm actually unsure whether it should work with a continuous x scale - at least the error message needs to be more informative. Any thoughts on this @sidiropoulos?

**Comment by sidiropoulos** [comment]
`geom_sina` shouldn't work with continuous scales. 
There is a check similar to `geom_boxplot` in `ggplot2` that uses the internal `has_groups()` function. I'm making a pull request with a fix for this bug.

**Comment by thomasp85** [comment]
Just a better error message will do

**Comment by sidiropoulos** [comment]
The error message is there, it can't be produced because the function is missing. It's a very short one, I added it in `sina.r`
