### ISSUE TITLE
geom_sina issue

### ISSUE THREAD

**Issue by jalali4** [thomasp85/ggforce#41]
Thanks for this nice additions. I noticed a minor issue with the geom_sina function that wanted to bring to your attention. It's probably a scaling vs width issue.

I have several hundred datapoints in the range -2000 to 6000. When I plot my datapoints using geom_sina(size=1) without any additional options, I don't get any jitter (or if there is, the default width is too small to notice). Visually they all line up in a straight line.

When I re-scale my data to range -2 to 6 (divide by 1000), I get a nice jitter with appropriate width. The geom_violin function works fine with appropriate width without a need to re-scale my data, but geom_sina doesn't. It should be easy to replicate on your end, but I can send you my data values if you like.

**Comment by thomasp85** [comment]
Can you provide a minimal example?

**Comment by sidiropoulos** [comment]
I guess this does it. 

```
df <- data.frame(x = rep(c("a", "b"), each = 1000),  
                 y = c(rnorm(1000, 2000, 3000), rnorm(1000, 4000, 3000)))

ggplot(df, aes(x, y)) + geom_sina()
ggplot(df, aes(x, y / 1000)) + geom_sina()
```

The problem is that the actual density is very low when the values are sparse. I'm now scaling `maxwidth`  properly to take into account data sparsity.

**Comment by theozhirsch** [comment]
Hi,
The problem is still occuring, for instance with the minimal example provided by sidiropoulos, and I don't understand how to use `maxwidth` to solve the problem. 

Thank you !

**Comment by JMLuther** [comment]
I have this issue continue to occur with various plots, and playing with `maxwitdth` doesn't seem to fix it.
example below for an example comparable in size to my dataset, but I've also had the issue with larger datasets.

``` r
library(tidyverse)
df <-
  data.frame(race.f = factor(sample(c("C", "AA"), 200, replace = T)),
             response = rnorm(200, 550, 200))
df %>% 
  ggplot(aes(race.f, response)) + 
  geom_boxplot() +
  ggforce::geom_sina()
```

![](https://i.imgur.com/jKO8R8b.png)

<sup>Created on 2018-10-30 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by JMLuther** [comment]
Occurs with larger n, adjusting maxwidth, and the geom_boxplot is not the issue either:

``` r
library(tidyverse)
df <-
  data.frame(race.f = factor(sample(c("C", "AA"), 1000, replace = T)),
             response = rnorm(1000, 550, 200))
df %>% 
  ggplot(aes(race.f, response)) + 
  # geom_boxplot() +
  ggforce::geom_sina(maxwidth = 0.9)
```

![](https://i.imgur.com/31bU90h.png)

<sup>Created on 2018-10-30 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by JMLuther** [comment]
installing the github versions of both ggforce(0.1.1) and ggplot2 (3.1.0.9000) fixes this issue, apparently.

``` r
df <-
  dplyr::data_frame(race.f = factor(sample(c("C", "AA"), 1000, replace = T)),
             response = rnorm(1000, 550, 200))

library(ggplot2, ggforce)
ggplot2::ggplot(df, aes(race.f, response)) + 
  geom_boxplot() +
  ggforce::geom_sina(maxwidth = 0.5)
```

![](https://i.imgur.com/XfHM5tr.png)

<sup>Created on 2018-10-30 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
