### ISSUE TITLE
scale="free" on facet_wrap_paginate throws error

### ISSUE THREAD

**Issue by Myles12345** [thomasp85/ggforce#42]
I noticed this whilst working with my own data.  I've reproduced using the diamond df below:   When scales is changed from its default ("fixed") - to (say) "free", you get the error -

Error in FUN(X[[i]], ...) : Unknown input

`# Calculate the number of pages with 9 panels per page
n_pages <- ceiling(
  length(levels(diamonds$cut)) * length(levels(diamonds$clarity)) / 9)`

`# Draw each page
for (i in seq_len(n_pages)) {
  print(ggplot(diamonds) +
    geom_point(aes(carat, price), alpha = 0.1) + 
    facet_wrap_paginate(~cut:clarity,  ncol = 3, nrow = 3, scales = "free", page = i))`

Traceback:
`19 stop("Unknown input") 
18 FUN(X[[i]], ...) 
17 lapply(grobs, height_cm) 
16 unlist(lapply(grobs, height_cm)) 
15 unit(max(unlist(lapply(grobs, height_cm))), "cm") 
14 FUN(newX[, i], ...) 
13 apply(axis_mat_x_top, 1, max_height) 
12 unit(apply(axis_mat_x_top, 1, max_height), "cm") 
11 f(...) 
10 FacetWrap$draw_panels(panels, layout, x_scales, y_scales, ranges, 
    coord, data, theme, params) 
9 f(...) 
8 self$draw_panels(panels, layout, x_scales, y_scales, ranges, 
    coord, data, theme, self$params) 
7 f(..., self = self) 
6 self$facet$render_panels(panels, self$panel_layout, self$panel_scales$x, 
    self$panel_scales$y, self$panel_ranges, coord, data, theme, 
    labels) 
5 f(..., self = self) 
4 layout$render(geom_grobs, data, plot$coordinates, theme, plot$labels) 
3 ggplot_gtable(data) 
2 print.ggplot(ggplot(diamonds) + geom_point(aes(carat, price), 
    alpha = 0.1) + facet_wrap_paginate(~cut:clarity, ncol = 3, 
    nrow = 3, scales = "free", page = i)) 
1 print(ggplot(diamonds) + geom_point(aes(carat, price), alpha = 0.1) + 
    facet_wrap_paginate(~cut:clarity, ncol = 3, nrow = 3, scales = "free", 
        page = i)) `

**Comment by thomasp85** [comment]
Please verify that you are running the latest version. This should have been fixed

**Comment by Myles12345** [comment]
My apologies -  yes, I changed CRAN mirror and pulled down 0.1.1 instead.  This issue is closed.   Thank you for all your amazing work - much appreciated!
