### ISSUE TITLE
alternative use of facet_zoom

### ISSUE THREAD

**Issue by GRousselet** [thomasp85/ggforce#44]
`facet_zoom()` points at something important lacking in `ggplot2`: a tool to link across figure panels.

Would there be a way to use `facet_zoom()` in which the zoomed area could be populated with different plots altogether? 

Concretely, this could be used when:

- the data from the zoomed area (a subset of the data in the original panel) are used to produce a different visualisation, and we want to indicate the origin of the data;

- all the data from the original panel are used in a different calculation, leading to a different visualisation in which the units cover a subset of the original units - for instance a linear fit is performed using all the data, but in the zoomed area we investigate the residuals in one area of the fit only.

**Comment by thomasp85** [comment]
My current plan for further improvements to `facet_zoom()` is to allow the user to specify which data rows should be shown in full, zoom and both. I'm thinking of a formula interface that should return a logical vector where `NA` indicates both and `TRUE`/`FALSE` is a switch between the two panels. Haven't quite nailed the API yet though...

I think your use cases could be handled (perhaps a bit clunky) with this?

**Comment by GRousselet** [comment]
Sounds like a good start. I'll see if I can contribute eventually...

**Comment by thomasp85** [comment]
Fixed in f979335
