### ISSUE TITLE
facet_zoom point labels

### ISSUE THREAD

**Issue by hfang-bristol** [thomasp85/ggforce#45]
Is it possible to only shown point labels  in the zoom-in panel (without showing point labels in the original panel)?

**Comment by crazyhottommy** [comment]
why is this closed? I have the same question. 
I also see someone asked https://stackoverflow.com/questions/45221783/ggforce-facet-zoom-labels-only-on-zoomed-example

Thank you very much.
Tommy

**Comment by crazyhottommy** [comment]
use the `zoom.data` argument
