### ISSUE TITLE
geom_sina with only one category

### ISSUE THREAD

**Issue by gaiusjaugustus** [thomasp85/ggforce#46]
So I often use geom_violin or geom_boxplot to look at just one category.  The standard way I do this is with something like the following

`ggplot(df, aes(x=1, y=Var)) + geom_violin()`

However, when trying to use geom_sina, I had to create a useless variable, because otherwise, I got the following error:
`Error in f(...) : could not find function "has_groups"`

The solution I've found, for now, is just the following:
```
df$Varx <- "Varx"
ggplot(df, aes(x=Varx, y=Var)) + geom_sina()
```

Thanks for the awesome package,
Gaius

**Comment by thomasp85** [comment]
Can I get you to install the latest version from GitHub and see if the problem persists?

**Comment by thomasp85** [comment]
Can you try with the GitHub version? This should hav been fixed

**Comment by gaiusjaugustus** [comment]
Sorry, just saw this.  I did install the github version and everything works properly.  Thank you.
