### ISSUE TITLE
aes colour not respected by geom_sina like in geom_violin

### ISSUE THREAD

**Issue by idot** [thomasp85/ggforce#47]
When the data is split by colour, then geom_sina should split the data like geom_violin does, but the points stay in the same x position.

```R
df <- data.frame(a=sample(LETTERS[1:6],1000,replace=TRUE), b=rnorm(1000),l=c(TRUE,FALSE))
ggplot(df, aes(x=a,y=b,colour=l)) + geom_violin() + geom_sina()
```

**Comment by thomasp85** [comment]
There is no promise that `geom_violin()` and `geom_sina()` works exactly alike. The beauty of `geom_sina` is that you can style observations directly and therefore add different colours inside each bin etc.

That being said, it should be possible to use `position_dodge()` with `geom_sina()` to obtain the desired result but this currently throws a warning without altering the plot. I'll look into this aspect

**Comment by thomasp85** [comment]
@sidiropoulos do you have time to look into this?

**Comment by sidiropoulos** [comment]
@thomasp85 I had a look and can't think of a quick way to use `position_dodge()`. I get the following: 

```
df <- data.frame(a=sample(LETTERS[1:6],1000,replace=TRUE), b=rnorm(1000),l=c(TRUE,FALSE))
ggplot(df, aes(x=a,y=b,colour=l)) + ggforce::geom_sina(position = position_dodge(width = 0.5))

Warning message:
position_dodge requires non-overlapping x intervals 
```

Do you have ideas for a workaround? I don't think I have time for this until next week.

**Comment by thomasp85** [comment]
I'll think about it a bit when I get the time

**Comment by insight8183** [comment]
I am having the same problem, as described above. I'd like to use Sinaplots for an upcoming paper of mine. Is it possible to publish a workaround (or solution)?

**Comment by insight8183** [comment]
There is now a workaround available, courtesy of Z. Lin: https://stackoverflow.com/questions/50410085/displaying-multiple-factors-with-sina-plots
