### ISSUE TITLE
using a vector in the raw scale to subset in facet_zoom

### ISSUE THREAD

**Issue by ginolhac** [thomasp85/ggforce#50]
I was very happy to see your demo if `facet_zoom()` on twitter. I didn't have a real application to test it until yesterday. And I would like to zoom in based on a chosen on the response raw scale with a numerical vector.

Before I was using `grid.arrange`

    gridExtra::grid.arrange(rr, rr + coord_cartesian(ylim = c(609, 611)) + theme(legend.position = "none"), nrow = 1, widths = c(0.65, 0.35))

![image](https://cloud.githubusercontent.com/assets/710181/21003207/58602f84-bd2a-11e6-9d3b-47cc8cfb078b.png)

Then, I tried `facet_zoom` using a naive approach
    ggforce::facet_zoom(y = c(500, 680), shrink = FALSE, zoom.size = 0.75)

It looks roughly ok, but:

- it introduced missing data, the naive approach does not create the appropriate logical vector to subset
- the zoom is on the left, would prefer it on the right and exchange the legend
- the chosen y-scale fits the dashed lines but are too zoomed in 
![image](https://cloud.githubusercontent.com/assets/710181/21003261/9e40581c-bd2a-11e6-9305-f01f0746664d.png)

the final idea was to create the logical vector on the continuous response using `dplyr::between`

    ggforce::facet_zoom(y = between(biomass, 609, 611), shrink = FALSE, zoom.size = 0.75)

but it is not like `coord_cartesian` to zoom in the plot, but select data.

the best I achieved was

![image](https://cloud.githubusercontent.com/assets/710181/21003438/a9432de2-bd2b-11e6-9cbd-c2f5d9f12f7b.png)

the code is there:

```
library(tidyverse)
read_tsv("https://raw.githubusercontent.com/LSRU/r_workshop/gh-pages/data/competition.txt") %>%
  ggplot(aes(x = clipping, y = biomass)) + geom_boxplot() + labs(x = "Competition treatment", colour = NULL, y = "Biomass") +
  geom_hline(aes(colour = "mean r10", yintercept = 610.6667), linetype = "dashed") +
  geom_hline(aes(colour = "clipping3", yintercept = 610.6667 - 0.08333), linetype = "dashed") +
  geom_hline(aes(colour = "mean (r5, r10)", yintercept = (610.6667 + 610.5) / 2), alpha = 0.6) +
  geom_hline(aes(colour = "mean r5", yintercept = 610.5), linetype = "dashed") + # -> rr
  #ggforce::facet_zoom(y = c(500, 680), shrink = FALSE, zoom.size = 0.75)
  ggforce::facet_zoom(y = between(biomass, 600, 615), shrink = FALSE, zoom.size = 0.75)
```

Thanks again for all the very nice developments you did!

**Comment by thomasp85** [comment]
I'm a bit unsure about what you're trying to achieve (might be because I'm tired)

The GitHub version now allows you to set zoom range directly using `xlim`and `ylim` arguments - Is that what you're requesting?

**Comment by ginolhac** [comment]
Tusind tak!!

didn't look into the dev version, yes it does what I want, thanks!

`ggforce::facet_zoom(ylim = c(610, 611), shrink = FALSE, zoom.size = 0.75)`

could we exchange the legend and zoom plot? So to have from left to right: legend, original, zoom?

thanks again!

![image](https://cloud.githubusercontent.com/assets/710181/21005126/d63127a2-bd33-11e6-8c87-7610107d0995.png)
