### ISSUE TITLE
ggforce.rdb missing

### ISSUE THREAD

**Issue by under-score** [thomasp85/ggforce#54]
a minor glitch
`devtools::install_github('thomasp85/ggforce')
Downloading GitHub repo thomasp85/ggforce@master
from URL https://api.github.com/repos/thomasp85/ggforce/zipball/master
Fehler in eapply(ns_env(pkg), force, all.names = TRUE) : 
  kann Datei '/Library/Frameworks/R.framework/Versions/3.3/Resources/library/ggforce/R/ggforce.rdb' nicht öffnen: No such file or directory`

**Comment by thomasp85** [comment]
I don't think this has anything to do with ggforce
