### ISSUE TITLE
Q: Why does ggforce require R 3.3?

### ISSUE THREAD

**Issue by friendly** [thomasp85/ggforce#55]
Is that absolutely necessary?  It makes to recommend to students or colleagues

**Comment by thomasp85** [comment]
It's mainly due to some errors cropping up on older r versions during the submission process. I didn't have time to fix it then but will look more into it before the next release and hopefully be able to remove the version requirement

**Comment by stphnlyd** [comment]
+1

I see the change to require R 3.3 was made in https://github.com/thomasp85/ggforce/commit/378fd163dc16a9f58baa051bd23181a757a65884, with commit message "Depend on latest tweenr version". But even latest tweenr requires only 3.2.0.

**Comment by thomasp85** [comment]
It has nothing to do with tweenr - it just inadvertently got lumped together with that change. I suspect some of the Rcpp code has a problem with older releases, but I haven't had time to investigate
