### ISSUE TITLE
facet_zoom with different data and different plot

### ISSUE THREAD

**Issue by zx8754** [thomasp85/ggforce#59]
Is it possible to have zoomed region to have different Y values and different type of plot?

Example:
```R
library(ggplot2)
library(ggforce)

#dummy data
set.seed(1)
df1 <- data.frame(x = 1:100, y = runif(100), zoom = c(rep("a", 30), rep("b", 20), rep("c", 50)))
df2 <- data.frame(x = 1:100, y = runif(100, 1, 10))

ggplot(df1, aes(x, y)) +
  geom_point() + 
  facet_zoom(x = zoom == "b")
```
![plot1](https://cloud.githubusercontent.com/assets/5212915/22973630/68dc032e-f376-11e6-9eef-2e964a9ecb1f.jpeg)

All great but this is not what I want. I need to have the zoomed region to have plot based on different data as Y value, and different plot type:
```R
gg1 <- ggplot(df1, aes(x, y)) + geom_point()
gg2 <- ggplot(df2, aes(x, y)) + geom_line()

#interseting area zoomed in with line plot
range(df1[ df1$zoom == "b", "x"])
# [1] 31 50
gg2zoom <- ggplot(df2[ df2$x >= 31 & df2$x <= 50, ], aes(x, y)) + 
  geom_line()

#merge plot vertically
cowplot::plot_grid(gg1, gg2zoom, nrow = 2)
```
![plot2](https://cloud.githubusercontent.com/assets/5212915/22973662/84609a60-f376-11e6-9f3c-e69b3ab6d3e9.jpeg)

I would want above plot with your type of shading to show zooming area, here is expected output with bit of Paintburshing:

![plot3](https://cloud.githubusercontent.com/assets/5212915/22973671/8f1d78a6-f376-11e6-89e8-f01e099a764d.jpg)

Possible? Maybe other workarounds?

**Comment by domiden** [comment]
I think it is not possible to achieve what you are looking for with `facet_zoom` function at current stage. Perhaps I'm wrong. However, one is able to specify which `geom_` will be recognised by the zoom function. As described in the package help and tweeted by @thomasp85 three month ago:

![[facet_zoom @thomasp85 (twitter)](https://twitter.com/thomasp85/status/806087011186733057)](https://pbs.twimg.com/media/Cy_L1pZWIAAki-g.jpg)

I tried several combination. However, it seems the axis range is set to dataset/variable with largest limit. In your case `y = [0, 10]`. The lower limit is provided by dataset 1  and the upper limit by dataset 2. 

I provided on of my half-backed plots as another example how to use `facet_zoom` with specified `geom`s. 

Hopefully, this comment was helpful in one way or another.  :dart:

# Data and plot example (slightly modified)

```r
set.seed(12345)
df1 <- data.frame(x = 1:100, y = runif(100), z = c(rep("a", 30), rep("b", 20), rep("c", 50)))
df2 <- data.frame(x = 1:100, y = runif(100, 1, 10))

ggplot(data = cbind(df1, zoom = FALSE), 
       aes(x, y)) +
  geom_point() + 
  geom_line(data = cbind(df2, zoom = TRUE)) +
  facet_zoom(x = z == "b", zoom.data = zoom)
```
![test plot](https://cloud.githubusercontent.com/assets/24540355/23319968/1220e2d8-fad9-11e6-8d57-d308fbfc967d.png)

# Another plot example

```r
p + 
  ggrepel::geom_text_repel(data = df %>%
                             cbind(., zoom = TRUE) %>%
                             dplyr::filter(stress < .28) %>%
                             dplyr::sample_n(50),
                           aes(label = id), size = 2.75) +
  ggrepel::geom_label_repel(data = df %>%
                              cbind(., zoom = TRUE) %>%
                              dplyr::filter(stress == min(stress)), 
                            aes(label = id), size = 2.75, colour = "#b12a90ff") +
  ggforce::facet_zoom(ylim = c(-.8, .8), xlim = c(-.8, .6), zoom.size = 1,
                      zoom.data = zoom)
```

![test plot 2](https://cloud.githubusercontent.com/assets/24540355/23321753/109acd90-fae1-11e6-95a9-5ce99c36bfae.png)

**Comment by nhuanmc** [comment]
Hi, is it possible to have multiple zooms in 1 plot? I take the plot from an earlier post as an example. There are 2 sites (25,50) and (60-80). Thanks
![84609a60-f376-11e6-9f3c-e69b3ab6d3e9](https://user-images.githubusercontent.com/50253288/128589756-5fc55285-ca76-4907-bfe6-7adcd7244fa9.jpg)
