### ISSUE TITLE
release facet_wrap_paginate using dev version of ggplot2?

### ISSUE THREAD

**Issue by daattali** [thomasp85/ggforce#6]
ggplot2 isn't released very often in the last few years, do you know if Hadley has plans of releasing it soon?

I was wondering why not releasing the paginate functions and simply specify the dev version of ggplot2 in the DESCRIPTION and travis. Of course it's a very selfish request :)

**Comment by daattali** [comment]
PS I tested it out and it's perfect. I tried using ggplus::facet_multiple but it was very clunky, didn't support outputting a specific page, and it would force print to the graphics device instead of returning a ggplot object. These functions are awesome :+1:

**Comment by thomasp85** [comment]
Glad you like it. It will not be long before the next release of ggplot2 so I'll hold it off until then
