### ISSUE TITLE
feature request a split geom_violin

### ISSUE THREAD

**Issue by RMHogervorst** [thomasp85/ggforce#62]
http://stackoverflow.com/questions/35717353/split-violin-plot-with-ggplot2

Like geom_violin but with an extra argument split = var
Often useful for comparing men vs women etc.

**Comment by Ax3man** [comment]
It's a bit unclear to me what the best implementation would be. I'd guess it's really more of a `position` and not a `split` aesthetic.

**Comment by mkoohafkan** [comment]
This geom would also address this [old `ggplot2` issue] (https://github.com/tidyverse/ggplot2/issues/2947) provided you could 1) use `color` aesthetic for the outline and `fill = NA` to remove the fill, and 2) choose to display the first group on the left or right (something like `flip = TRUE`). I actually used a modified version of the code in the SO answer to achieve the result I needed.

**Comment by thomasp85** [comment]
This is now handled by [gghalves](https://github.com/erocoar/gghalves)

**Comment by RMHogervorst** [comment]
Awesome! Thanks for reaching out!
