### ISSUE TITLE
Support plotly by adding to_basic.GeomSina() style methods

### ISSUE THREAD

**Issue by jmw86069** [thomasp85/ggforce#69]
To support ggplotly, each Geom* type needs its own to_basic.*() function. I was able to make geom_sina() work in ggplotly() by adding this function:

    to_basic.GeomSina <- function
    (data, prestats_data, layout, params, p, ...)
    {
       plotly:::prefix_class(data, "GeomPoint");
    }

I'm not sure the appropriate way to call the plotly:::prefix_class(), I defer to you on the proper way to do that.

More info here: https://cpsievert.github.io/plotly_book/translating-custom-ggplot2-geoms.html

Reproducible example (I included the geom_jitter entries for comparison):

    library(plotly);
    library(ggforce);
    df <- data.frame(a=sample(LETTERS[1:6],1000,replace=TRUE), b=rnorm(1000),l=c(TRUE,FALSE));
    ggplot(df, aes(x=a,y=b,colour=a)) + geom_violin() + geom_sina();
    ggplotly(ggplot(df, aes(x=a,y=b,colour=a)) + geom_violin() + geom_sina());
    
    ggplot(df, aes(x=a,y=b,colour=a)) + geom_violin() + geom_jitter();
    ggplotly(ggplot(df, aes(x=a,y=b,colour=a)) + geom_violin() + geom_jitter());

PS - I love your work!

**Comment by thomasp85** [comment]
I'll not have time to port the geoms in ggforce to poorly for the foreseeable future so I'm closing.
