### ISSUE TITLE
facet_wrap_paginate

### ISSUE THREAD

**Issue by guiastrennec** [thomasp85/ggforce#7]
Nice work on ggforce and looking forward to the new release with ggplot2 2.2.0. In the meantime 2 questions on facet_wrap_paginate:
- Is it possible to print all pages at once without using the `for` loop?
- Is it possible to keep the requested layout e.g. `ncol = 2, nrow = 2` on the last page even if there is in this case only 2 panels left to plot?

**Comment by thomasp85** [comment]
Good questions :-)

For the first - I plan to provide some sort of helper function that facilitates this, but it will not be part of `facet_*_paginate` itself. For the second, this is something I've thought about too, without prioritising it a lot so it is not part of the current implementation. I'll not rule it out though...

**Comment by daattali** [comment]
ggplot2.2.0 is out! Can we have this feature now pretty please? :)

**Comment by thomasp85** [comment]
It has not even been a day...:-)

**Comment by daattali** [comment]
But it's been well over a minute. What am I paying you for!

(take your time, just wanted to place a reminder because I'm sure you have a lot of different projects going on and this one might not be a priority that's on your mind)

**Comment by thomasp85** [comment]
Believe it or not but ggforce and ggraph are currently on top of my "projects-I-do-and-enjoy". Thus below leftover PhD articles and the work that puts bread on the table, but above the rest you find on my GitHub profile

**Comment by mthernando** [comment]
Thanks Thomas for your great work! I am using facet_wrap_paginate and it works OK with the first page, but when trying to print the second one it fails with the following error.  

> plot_bar(taxa.norm_phylum, "Substrate", fill='SampleID', title='Phylum relative abundance -Substrate-')+geom_bar(stat='identity', position='stack')+facet_wrap_paginate(~Phylum, ncol = 3, nrow=3, scales = 'free', page = 2)
Error in FUN(X[[i]], ...) : Unknown input

Could you please help to me? (I've updated the package to the latest version, released just 17h ago)

Thanks

María

**Comment by thomasp85** [comment]
Whst is `plot_bar`? It is not part of either ggplot2 or ggforce...

**Comment by mthernando** [comment]
Sorry, this is from phyloseq package, that use ggplot2 to plot several objects built from metagenomic studies. I have used phyloseq functions + ggplot2 options and it works properly, but I didn't realized that perhaps in this case it does not work.

**Comment by thomasp85** [comment]
It could be - phyloseq is probably optimised to work correctly with ggplot2 functions. If you can reproduce the error with pure ggforce/ggplot2 calls I'll look into it. Otherwise I suggest contacting the authors of phyloseq

**Comment by mthernando** [comment]
Yes, it works properly with ggplot2, and it seems to fail with phyloseq. Thanks!
