### ISSUE TITLE
Feature Request: facet_pairs as an alternative to ggpairs, pairs, and splom

### ISSUE THREAD

**Issue by wdkrnls** [thomasp85/ggforce#72]
The traditional stat 101 way of looking at multivariate response data is with a scatter plot matrix. While I can make these figures within the ggplot2/tidy data framework using ggpairs, I always forget how to use it! Instead, I'd love a facet extension that assumed the data was gathered into two columns: variable, value. For example, imagine a data set with 4 columns: a w column classifying group membership, and 3 numeric response columns x, y, and z. Then, it would be easy for me to remember to write the following code to see the scatter plot matrix:

```
data %>%
  gather(variable, value, c(x, y, z)) %>%
  ggplot(aes(y = value, color = w)) +
    geom_point() +
    facet_pairs(~ variable, triangle = "upper")
```

**Comment by Ax3man** [comment]
I guess code of this form would fail, since `geom_point` is not getting an `x` aesthetic.

**Comment by wdkrnls** [comment]
Yes. That's true, but maybe geom = "point" could be defined as an argument
(as default) since x would exist at drawing time.

**Comment by wdkrnls** [comment]
I also realized that `triangle` is not a good name for the argument, since it would be really nice if this function could optionally give a wrapped layout, potentially ordered by a scoring function like correlation.

```
data %>%
  gather(variable, value, c(x, y, z)) %>%
  ggplot(aes(y = value, color = w)) +
    facet_pairs(~ variable, layout = "wrap", order = ~ rev(order(cor(x, y))))
```

**Comment by thomasp85** [comment]
This could potentially be done to some extend, but it will never be as powerful as ggpairs (I've actually thought a great deal about this in the past).

Defining the geom in the facet is breaking every ggplot2 convention and will not happen (in ggforce at least)...
