### ISSUE TITLE
How do you access geom_bezier() "Computed Variables" : x,y,index

### ISSUE THREAD

**Issue by statsccpr** [thomasp85/ggforce#85]
Hi, following the suggestion posed here
https://github.com/tidyverse/ggplot2/issues/2372#issuecomment-351831539

I looked into ?ggforce::geom_bezier()

Its help manual subsection on Computed variables, seems to be what I'm looking for.

```
x, y
The interpolated point coordinates

index
The progression along the interpolation mapped between 0 and 1

```

But doing

```
beziers <- data.frame(
  x = c(1, 2, 3, 4, 4, 6, 6),
  y = c(0, 2, 0, 0, 2, 2, 0),
  type = rep(c('cubic', 'quadratic'), c(3, 4)),
  point = c('end', 'control', 'end', 'end', 'control', 'control', 'end')
)

bez = geom_bezier(aes(x= x, y = y, group = type, linetype = type), 
                 data = beziers)
ls(bez)  
```

I do not see how to access the interpolated coordinates or index.

How would one go about it?

**Comment by thomasp85** [comment]
This is not how Geom/Stat objects work. The computed variables are available to the aesthetic specification but not outside of the object... I think `grid` has some functionalities for calculating points along a bezier directly but I'm not sure
