### ISSUE TITLE
facet_zoom

### ISSUE THREAD

**Issue by GuangchuangYu** [thomasp85/ggforce#9]
## x and y should all be provided 
If only provide `x` or `y`, it fails even with the example you posted in twitter.

```
> p + facet_zoom(x = Species != 'setosa', y = Species == 'versicolor')
> p + facet_zoom(y = Species == 'versicolor')
Error in x_scales[[2]] : subscript out of bounds
```

## fail if it was wrapped in a function

```r
require(ggtree)
tr <- rtree(50)
p <- ggplot(tr, aes(x, y)) + geom_tree2() + geom_label(aes(label=node))

tree_zoom <- function(treeview, node, ...) {    
    treeview + facet_zoom(xy = node %in% get.offspring.df(treeview$data, node), ...)
}

tree_zoom(ggplot(tr, aes(x, y)) + geom_tree2() + geom_label(aes(label=node)), node=84)
```

![screen shot 2016-09-30 at 10 40 43 am](https://cloud.githubusercontent.com/assets/626539/18979054/5a6e3e80-86fa-11e6-9328-43518a9419f6.png)

## ugly when not using `theme_grey`

```r
p1 <- ggplot(tr, aes(x, y)) + geom_tree2() + geom_label(aes(label=node))+ theme_tree()
p1 <- p1 + facet_zoom(xy = node %in% get.offspring.df(p1$data, 84))

multiplot(p1, p1+theme_grey(), ncol=2)
```

![screen shot 2016-09-30 at 10 39 23 am](https://cloud.githubusercontent.com/assets/626539/18979043/474b8a06-86fa-11e6-9e84-1293c5f2ebcb.png)

**Comment by thomasp85** [comment]
Thanks. The first was a bug introduced during refactoring - it has been fixed now.

For the second - I suspect that your plot data contains a column named node? If so this will have precedence over the node variable defined in your wrapper function (this is the case with all NSE in ggplot2)

For the third. The style is taken from the strip theming. It is not generally possible to predict a nice look so facet_zoom uses the strip background style as default as it is expected that the strip style looks nice with the overall theme. You can modify the strip style or directly set the zoom style with `theme(zoom = element_rect(...), validate = FALSE)`

**Comment by GuangchuangYu** [comment]
I use `strip.background`:
```
p + theme(strip.background=element_rect(fill=NA, linetype='dashed'))
```

`fill` works, but `linetype` has no effect.

If I use `theme(zoom)`, it complains that:

```
Error in (function (el, elname)  :
  "zoom" is not a valid theme element name.
```

```
> packageVersion("ggplot2")
[1] ‘2.1.0.9001’
> packageVersion("ggforce")
[1] ‘0.1.0’
>
```

**Comment by thomasp85** [comment]
Oh - I overlooked linetype. Thanks!

As it is now you need to set `validate=FALSE` when adding non-standard theme elements such as zoom
