### ISSUE TITLE
geom_ellipsis() not in NAMESPACE when version 0.1.1 is installed on Windows

### ISSUE THREAD

**Issue by kevinwolz** [thomasp85/ggforce#92]
I have installed ggforce on a Mac and a PC. geom_ellipsis() works great on the Mac, but when I called ggforce::geom_ellipsis() on the PC, I got an error message that "geom_ellipsis is not an exported object from 'namespace:ggforce':. I checked the NAMESPACE file of ggforce directly on the PC, and geom_ellipsis() is indeed not included! I have never experienced this before with a package, so I have no idea what's going on. I hope that geom_ellipsis() works on Windows because it is critical to my new package (which I have been developing on the Mac). 

Both computers are running R 3.4.3. Any other info I can provide to help?

**Comment by thomasp85** [comment]
My guess is that you installed the development version of ggforce at some point on your Mac. geom_ellipsis is not on CRAN for any system yet.

ggforce is waiting for a ggplot2 update on CRAN before it can be updated on CRAN, so I'm afraid your own package will be affected by this dependency as well...

**Comment by kevinwolz** [comment]
@thomasp85 it looks like you first included geom_ellipse() in releasing version 0.2.0. Is this a direct replacement for geom_ellipsis() - just a name change?

**Comment by thomasp85** [comment]
yes... it is really a typo fix as *ellipsis* is ... (three dots). I was young and foolish when I first made that geom 🙂
