### ISSUE TITLE
Feature Request: Make Legends with `facet_*_paginate` look like `drop=TRUE` is Set

### ISSUE THREAD

**Issue by billdenney** [thomasp85/ggforce#93]
When generating a `facet_*_paginate` figure, I'd like to have the ability to make the legend only show the values in the current figure page.  I see that there is a `drop` argument to the `facet_*_paginate` functions, but it appears to apply at the level of all the data.  I'd like something like `drop_page` which would apply at the level of the data on the current page.

``` r
library(ggforce)                                                     
#> Loading required package: ggplot2
unique(mtcars[order(mtcars$carb),                                    
c("cyl", "carb")])                                                   
#>                   cyl carb
#> Datsun 710          4    1
#> Hornet 4 Drive      6    1
#> Hornet Sportabout   8    2
#> Merc 240D           4    2
#> Merc 450SE          8    3
#> Mazda RX4           6    4
#> Duster 360          8    4
#> Ferrari Dino        6    6
#> Maserati Bora       8    8
# I want to have the optiont to make this legend not show 8 cylinders
ggplot(mtcars,                                                       
aes(x=wt, y=mpg, colour=factor(cyl))) +                              
geom_point() +                                                       
facet_grid_paginate(~carb, nrow=1, ncol=1, page=1)                   
```

![](https://i.imgur.com/XBiUWiJ.png)

**Comment by thomasp85** [comment]
This would require considerably reengineering of the whole implementation unfortunately, and is also a bit out of scope - the paginate facetting is meant to literally be exactly like the non-paginated facets except spread out on multiple pages

**Comment by billdenney** [comment]
That's fair.  Thanks for the quick response.
