### ISSUE TITLE
Where are the voronoi geoms?

### ISSUE THREAD

**Issue by GarryGelade** [thomasp85/ggforce#94]
I downloaded the latest version of ggforce (0.1.1) from CRAN, but it doesn't have the voronoi geoms, This example:

`ggplot(iris, aes(Sepal.Length, Sepal.Width)) +
  geom_voronoi_tile(aes(fill = Species)) +
  geom_voronoi_segment() +
  geom_text(aes(label = ..nsides.., size = ..vorarea..),
            stat = 'delvor_summary', switch.centroid = TRUE)
`
gives the following error

> could not find function "geom_voronoi_tile"

Where can I find the voronoi geoms?

**Comment by thomasp85** [comment]
Still only available in the dev version on GitHub
