### ISSUE TITLE
set fill argument error of geom_arc_bar

### ISSUE THREAD

**Issue by cardiomoon** [thomasp85/ggforce#95]
Thank you for nice package !
I have experience of setting fill argument error of geom_arc_bar.
Here is a reproducible example.

```
require(ggforce)
pie <- data.frame(
    state = c('eaten', 'eaten but said you didn\'t', 'cat took it', 
              'for tonight', 'will decompose slowly'),
    focus = c(0.2, 0, 0, 0, 0),
    start = c(0, 1, 2, 3, 4),
    end = c(1, 2, 3, 4, 2*pi),
    amount = c(4,3, 1, 1.5, 6),
    stringsAsFactors = FALSE
)
```

I'd like to set the fill argument with rainbow(5).

```
myfillcolor=rainbow(5)

p <- ggplot(data=pie) + theme_no_axes() + coord_fixed()
```

This code makes barplot without error 

```
p + geom_col(aes(x=state,y=amount),fill=myfillcolor)
```

But this code makes error

```
p + geom_arc_bar(aes(x0 = 0, y0 = 0, r0 = 0, r = 1, start = start, end = end, 
                     ),fill=myfillcolor)
```
Error: Aesthetics must be either length 1 or the same as the data (368): fill

**Comment by Thonnard** [comment]
That is because you pass myfillcolor (containing 5 colours)to fill outside aes. This should work:

`p + geom_arc_bar(aes(x0 = 0, y0 = 0, r0 = 0, r = 1, start = start, end = end, fill=myfillcolor ))`

Good luck
