### ISSUE TITLE
facet_zoom color

### ISSUE THREAD

**Issue by viniciusvgp** [thomasp85/ggforce#98]
Hi, 

Is there a way to change the black/gray colors used to highlight the zoomed area?
In the code there is something like `theme$zoom.x$colour`, how can I control it when calling facet_zoom?

Thanks

**Comment by thomasp85** [comment]
It takes the values from the strip.background theme element as it is currently not possible to add new theme elements to ggplot2

**Comment by teunbrand** [comment]
Hi Thomas,

I know this is an old issue, but with the custom theme elements in ggplot2 v3.3.0 this should now be possible. Would you consider it if I were to prepare a PR that sets and uses a new theme element `ggforce.zoom.(x|y)` that inherits from `strip.background` with `ggplot2::register_theme_elements()`?

Best wishes

**Comment by thomasp85** [comment]
yes. this was always the plan but I haven't had time to look into ggforce lately. a pr is very welcome
