### ISSUE TITLE
facet_zoom highlights wrong context of the data

### ISSUE THREAD

**Issue by IndrajeetPatil** [thomasp85/ggforce#99]
The `facet_zoom` works fine in terms of selecting and displaying the right range of the data but somehow shows incorrect context from which the data was taken. Am I doing something wrong?

``` r


# loading needed libraries
library(ggplot2)
library(ggforce)

# creating a dataframe
df <-
  dplyr::filter(
    .data = mpg,
    manufacturer == "ford" |
      manufacturer == "dodge" |
      manufacturer == "nissan" | manufacturer == "audi"
  )

# zooming in on the axes
ggplot(data = df, mapping = aes(x = manufacturer, y = class)) +
  geom_jitter() +
  facet_zoom(x = manufacturer == "ford" | manufacturer == "nissan")
```

![](https://i.imgur.com/EIMHPIJ.png)

Created on 2018-06-30 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by thomasp85** [comment]
facet_zoom really doesn't support zooming on discrete scales, for various reasons. I have added proper errors instead of the current silent fail
